import {Store, uid} from './store.js';
import {money,fmtTime,dt,escapeHtml,beep} from './utils.js';

const store=new Store();
const app=document.getElementById('app');
const modalRoot=document.getElementById('modal-root');
const toastEl=document.getElementById('toast');
let route='arena';
let ownerSection='dashboard';
let typeFilter='all';
let alarmed=new Set();
let loginRole='operator';

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=(msg)=>{toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1800)};
const closeModal=()=>modalRoot.innerHTML='';
const modal=(title,body,footer='')=>{modalRoot.innerHTML=`<div class="modal-backdrop" data-action="close-modal-bg"><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h2>${title}</h2><button class="close-btn" data-action="close-modal">✕</button></div>${body}${footer?`<div class="modal-footer">${footer}</div>`:''}</div></div>`};

function nav(){
  const user=store.get().currentUser;
  const items=[['arena','🏁','Arena'],['queue','👥','Queue'],['rides','🧾','Rides'],['batteries','🔋','Batteries']];
  if(user?.role==='owner')items.push(['owner','⚙️','Owner']); else items.push(['more','☰','More']);
  return `<nav class="bottom-nav">${items.map(([r,i,l])=>`<button class="nav-btn ${route===r?'active':''}" data-route="${r}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`
}
function shell(content){const u=store.get().currentUser; return `<div class="app-shell"><header class="topbar"><div class="brand"><img src="./assets/kas-logo.png" alt="KAS"><div><div class="brand-title">KAS RC Arena</div><div class="brand-sub">Fleet • Ride • Battery</div></div></div><div class="top-actions"><span class="role-chip">${u?.role==='owner'?'Owner':'Operator'}</span><button class="icon-btn" data-action="logout" title="Logout">↪</button></div></header>${nav()}${content}</div>`}

function loginView(){app.innerHTML=`<div class="login"><div class="login-card"><img class="login-logo" src="./assets/kas-logo.png" alt="KAS"><h1>RC Arena Control</h1><p>Offline-first counter and owner management</p><div class="seg"><button data-login-role="operator" class="${loginRole==='operator'?'active':''}">Operator</button><button data-login-role="owner" class="${loginRole==='owner'?'active':''}">Owner</button></div><div class="field"><label>${loginRole==='owner'?'Owner':'Operator'} PIN</label><input id="pin" class="input pin" type="password" inputmode="numeric" maxlength="8" placeholder="••••"></div><button class="btn primary block" data-action="login" style="margin-top:14px">Enter KAS RC Arena</button><p class="subtle">Initial demo PINs: Operator 1111 • Owner 1234. Change them in Owner → Business.</p></div></div>`; setTimeout(()=>$('#pin')?.focus(),50)}

function currentRide(vehicleId){return store.get().rides.find(r=>r.vehicleId===vehicleId && ['active','paused','time_up'].includes(r.status));}
function todayRides(){const d=new Date(); d.setHours(0,0,0,0); return store.get().rides.filter(r=>r.startAt>=d.getTime());}
function todaySales(){const ids=new Set(todayRides().map(r=>r.id)); return store.get().payments.filter(p=>ids.has(p.rideId)).reduce((a,b)=>a+b.amount,0)}
function vehicleType(v){return store.get().vehicleTypes.find(x=>x.id===v.typeId)}
function vehicleBattery(v){const s=store.get();return (v.batteryIds||[]).map(id=>s.batteries.find(b=>b.id===id)).filter(Boolean)}
function statusText(st){return ({available:'Available',in_ride:'In Ride',time_up:'Time Up',charging:'Charging',maintenance:'Maintenance',paused:'Paused',inactive:'Inactive'})[st]||st}

function arenaView(){
  const s=store.get(), rides=todayRides(), active=s.vehicles.filter(v=>['in_ride','time_up'].includes(v.status)).length, avail=s.vehicles.filter(v=>v.status==='available').length;
  const filters=[['all','All'],...s.vehicleTypes.filter(x=>x.active).map(x=>[x.id,`${x.icon} ${x.name}`])];
  const vehicles=s.vehicles.filter(v=>typeFilter==='all'||v.typeId===typeFilter);
  const content=`<main class="page"><div class="page-head"><div><h1>Live Arena</h1><p>Run every ride from one screen.</p></div><button class="btn secondary small" data-action="quick-queue">+ Queue</button></div>
  <section class="metrics"><div class="metric"><div class="label">Today's Sales</div><div class="value">${money(todaySales())}</div><div class="tiny">Cash + UPI + other</div></div><div class="metric"><div class="label">Active</div><div class="value">${active}</div><div class="tiny">vehicles on ride</div></div><div class="metric"><div class="label">Available</div><div class="value">${avail}</div><div class="tiny">ready to start</div></div><div class="metric"><div class="label">Today's Rides</div><div class="value">${rides.length}</div><div class="tiny">all sessions</div></div></section>
  <div class="section-title">Fleet</div><div class="filter-row">${filters.map(f=>`<button class="filter-btn ${typeFilter===f[0]?'active':''}" data-filter="${f[0]}">${f[1]}</button>`).join('')}</div>
  <div class="vehicle-grid" style="margin-top:12px">${vehicles.map(vehicleCard).join('')||'<div class="empty">No vehicles in this category.</div>'}</div></main>`;
  app.innerHTML=shell(content);
}

function vehicleCard(v){const t=vehicleType(v),r=currentRide(v.id),bats=vehicleBattery(v); let cls=''; if(r?.status==='time_up')cls='time-up'; else if(r?.status==='active' && r.endAt-Date.now()<=store.get().business.warningSeconds*1000)cls='warning'; const batteryTxt=bats.length?bats.map(b=>b.code).join(', '):'Not assigned';
  if(!r) return `<article class="vehicle-card"><div class="vehicle-head"><div><div class="vehicle-name">${t?.icon||'🎮'} ${escapeHtml(v.name)}</div><div class="vehicle-code">${escapeHtml(v.code)}</div></div><span class="status s-${v.status}">${statusText(v.status)}</span></div><div class="ride-main"><div class="customer">${v.status==='available'?'Ready for next customer':statusText(v.status)}</div><div class="ride-meta">${t?.name||'Vehicle'}</div></div><div class="battery-line"><span>Battery</span><strong>${escapeHtml(batteryTxt)}</strong></div><div class="actions">${v.status==='available'?`<button class="btn primary" data-action="start-ride" data-id="${v.id}">+ Start Ride</button>`:''}${v.status!=='in_ride'?`<button class="btn secondary small" data-action="vehicle-status" data-id="${v.id}">Status</button>`:''}<button class="btn secondary small" data-action="swap-battery" data-id="${v.id}">Battery</button></div></article>`;
  const remaining=r.status==='paused'?r.pausedRemainingMs:Math.max(0,r.endAt-Date.now()); const pkg=store.get().packages.find(p=>p.id===r.packageId); const extButtons=store.get().extensions.filter(e=>e.profileId===v.extensionProfileId&&e.active).sort((a,b)=>a.sort-b.sort).slice(0,2);
  return `<article class="vehicle-card ${cls}"><div class="vehicle-head"><div><div class="vehicle-name">${t?.icon||'🎮'} ${escapeHtml(v.name)}</div><div class="vehicle-code">${escapeHtml(v.code)}</div></div><span class="status s-${r.status}">${statusText(r.status)}</span></div><div class="ride-main"><div class="timer" data-timer="${r.id}">${fmtTime(remaining)}</div><div class="customer">${escapeHtml(r.customerName)}</div><div class="ride-meta">${escapeHtml(pkg?.name||'Ride')} • ${pkg?.minutes||0} min • ${money(r.totalAmount)}</div></div><div class="battery-line"><span>Battery</span><strong>${escapeHtml(batteryTxt)}</strong></div><div class="actions">${extButtons.map(e=>`<button class="btn secondary small" data-action="quick-extend" data-ride="${r.id}" data-ext="${e.id}">${e.name} ${money(e.price)}</button>`).join('')}<button class="btn secondary small" data-action="extend-ride" data-id="${r.id}">More</button>${r.status==='paused'?`<button class="btn warning small" data-action="resume-ride" data-id="${r.id}">Resume</button>`:`<button class="btn ghost small" data-action="pause-ride" data-id="${r.id}">Pause</button>`}<button class="btn ghost small" data-action="swap-battery" data-id="${v.id}" data-ride="${r.id}">Battery</button><button class="btn ${r.status==='time_up'?'success':'danger'} small" data-action="complete-ride" data-id="${r.id}">${r.status==='time_up'?'Complete':'End'}</button></div></article>`;
}

function queueView(){const waiting=store.get().queue.filter(q=>q.status==='waiting'); app.innerHTML=shell(`<main class="page"><div class="page-head"><div><h1>Waiting Queue</h1><p>Keep the next customers ready when all vehicles are busy.</p></div><button class="btn primary small" data-action="add-queue">+ Add</button></div><div class="list">${waiting.map((q,i)=>`<div class="list-row"><div class="list-main"><div class="list-title">${i+1}. ${escapeHtml(q.name)}</div><div class="list-sub">${escapeHtml(q.mobile||'No mobile')} • waiting ${Math.max(1,Math.round((Date.now()-q.createdAt)/60000))} min</div></div><div class="actions"><button class="btn primary small" data-action="serve-queue" data-id="${q.id}">Start</button><button class="btn ghost small" data-action="remove-queue" data-id="${q.id}">Remove</button></div></div>`).join('')||'<div class="empty">No customers waiting.</div>'}</div></main>`)}

function ridesView(){const rides=store.get().rides.slice(0,150); app.innerHTML=shell(`<main class="page"><div class="page-head"><div><h1>Ride History</h1><p>Every session and extension is recorded.</p></div></div><div class="list">${rides.map(r=>{const v=store.get().vehicles.find(x=>x.id===r.vehicleId),p=store.get().packages.find(x=>x.id===r.packageId); return `<button class="list-row" style="color:inherit;text-align:left" data-action="ride-detail" data-id="${r.id}"><div class="list-main"><div class="list-title">${escapeHtml(r.customerName)} • ${escapeHtml(v?.code||'Vehicle')}</div><div class="list-sub">${r.number} • ${dt(r.startAt)} • ${escapeHtml(p?.name||'Ride')}${r.extensions.length?` • +${r.extensions.reduce((a,e)=>a+e.minutes,0)} min`:''}</div></div><div class="list-right"><div class="amount">${money(r.totalAmount)}</div><span class="badge ${r.status==='completed'?'green':r.status==='time_up'?'red':'blue'}">${statusText(r.status)}</span></div></button>`}).join('')||'<div class="empty">No rides yet.</div>'}</div></main>`)}

function batteriesView(){const s=store.get(); const counts={ready:0,in_use:0,charging:0,maintenance:0}; s.batteries.forEach(b=>counts[b.status]=(counts[b.status]||0)+1); const groups=[['ready','Ready'],['in_use','In Use'],['charging','Charging'],['maintenance','Issue / Maintenance']]; app.innerHTML=shell(`<main class="page"><div class="page-head"><div><h1>Battery Station</h1><p>Manage spare batteries, swaps and charging.</p></div>${s.currentUser.role==='owner'?'<button class="btn primary small" data-action="add-battery">+ Battery</button>':''}</div><section class="metrics"><div class="metric"><div class="label">Ready</div><div class="value">${counts.ready||0}</div></div><div class="metric"><div class="label">In Use</div><div class="value">${counts.in_use||0}</div></div><div class="metric"><div class="label">Charging</div><div class="value">${counts.charging||0}</div></div><div class="metric"><div class="label">Issues</div><div class="value">${counts.maintenance||0}</div></div></section>${groups.map(([st,label])=>`<div class="section-title">${label}</div><div class="list">${s.batteries.filter(b=>b.status===st).map(batteryRow).join('')||`<div class="empty">No ${label.toLowerCase()} batteries.</div>`}</div>`).join('')}</main>`)}
function batteryRow(b){const s=store.get(),bt=s.batteryTypes.find(x=>x.id===b.typeId),v=s.vehicles.find(x=>x.id===b.assignedVehicleId); return `<div class="list-row"><div class="list-main"><div class="list-title">🔋 ${escapeHtml(b.code)} <span class="badge ${b.status==='ready'?'green':b.status==='charging'?'amber':b.status==='maintenance'?'red':'blue'}">${b.status.replace('_',' ')}</span></div><div class="list-sub">${escapeHtml(bt?.name||'Battery')} • ${b.cycles||0} cycles${v?` • ${escapeHtml(v.code)}`:''}</div></div><div class="actions">${b.status==='charging'?`<button class="btn success small" data-action="battery-ready" data-id="${b.id}">Mark Ready</button>`:''}${b.status==='ready'?`<button class="btn warning small" data-action="battery-charge" data-id="${b.id}">Charge</button>`:''}<button class="btn ghost small" data-action="battery-edit" data-id="${b.id}">Edit</button></div></div>`}

function moreView(){app.innerHTML=shell(`<main class="page"><div class="page-head"><div><h1>More</h1><p>Operator utilities.</p></div></div><div class="list"><button class="list-row" data-route="batteries" style="color:inherit"><div class="list-main"><div class="list-title">🔋 Battery Station</div><div class="list-sub">Ready, charging and in-use batteries</div></div><span>›</span></button><button class="list-row" data-route="rides" style="color:inherit"><div class="list-main"><div class="list-title">🧾 Ride History</div><div class="list-sub">Review completed and active rides</div></div><span>›</span></button></div></main>`)}

function ownerView(){const sections=[['dashboard','Dashboard'],['fleet','Fleet'],['pricing','Pricing'],['battery','Battery Setup'],['business','Business'],['backup','Backup']]; const body=ownerSectionView(); app.innerHTML=shell(`<main class="page"><div class="page-head"><div><h1>Owner Hub</h1><p>Configuration and performance controls.</p></div></div><div class="owner-grid"><aside class="card owner-menu">${sections.map(s=>`<button class="menu-btn ${ownerSection===s[0]?'active':''}" data-owner-section="${s[0]}">${s[1]}</button>`).join('')}</aside><section>${body}</section></div></main>`)}
function ownerSectionView(){const s=store.get(); if(ownerSection==='dashboard'){const rides=todayRides(); const completed=rides.filter(r=>r.status==='completed'); const cash=s.payments.filter(p=>new Date(p.ts).toDateString()===new Date().toDateString()&&p.method==='Cash').reduce((a,b)=>a+b.amount,0); const upi=s.payments.filter(p=>new Date(p.ts).toDateString()===new Date().toDateString()&&p.method==='UPI').reduce((a,b)=>a+b.amount,0); return `<div class="metrics"><div class="metric"><div class="label">Today Revenue</div><div class="value">${money(todaySales())}</div></div><div class="metric"><div class="label">Rides</div><div class="value">${rides.length}</div></div><div class="metric"><div class="label">Cash</div><div class="value">${money(cash)}</div></div><div class="metric"><div class="label">UPI</div><div class="value">${money(upi)}</div></div></div><div class="section-title">Vehicle Performance</div><div class="list">${s.vehicles.map(v=>{const vr=s.rides.filter(r=>r.vehicleId===v.id);return `<div class="list-row"><div><div class="list-title">${escapeHtml(v.code)} • ${escapeHtml(v.name)}</div><div class="list-sub">${vr.length} total rides</div></div><div class="amount">${money(vr.reduce((a,r)=>a+r.totalAmount,0))}</div></div>`}).join('')}</div>`}
 if(ownerSection==='fleet') return `<div class="card"><div class="page-head"><div><h1 style="font-size:20px">Fleet</h1><p>Any RC vehicle type can be added without code changes.</p></div><button class="btn primary small" data-action="add-vehicle">+ Vehicle</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Vehicle</th><th>Type</th><th>Status</th><th>Battery</th><th></th></tr></thead><tbody>${s.vehicles.map(v=>`<tr><td><strong>${escapeHtml(v.code)}</strong><br><span class="subtle">${escapeHtml(v.name)}</span></td><td>${escapeHtml(vehicleType(v)?.name||'')}</td><td>${statusText(v.status)}</td><td>${escapeHtml(vehicleBattery(v).map(b=>b.code).join(', ')||'—')}</td><td><button class="btn secondary small" data-action="edit-vehicle" data-id="${v.id}">Edit</button></td></tr>`).join('')}</tbody></table></div></div><div class="section-title">Vehicle Types</div><div class="card"><div class="list">${s.vehicleTypes.map(t=>`<div class="list-row"><div><div class="list-title">${t.icon} ${escapeHtml(t.name)}</div><div class="list-sub">${s.vehicles.filter(v=>v.typeId===t.id).length} vehicles</div></div></div>`).join('')}</div><button class="btn secondary" style="margin-top:10px" data-action="add-vehicle-type">+ Add Vehicle Type</button></div>`;
 if(ownerSection==='pricing') return `<div class="card" style="margin-bottom:12px"><div class="page-head"><div><h1 style="font-size:20px">Pricing Profiles</h1><p>Create separate pricing for cars, boats, excavators, trucks or any future vehicle.</p></div><div class="actions"><button class="btn secondary small" data-action="add-pricing-profile">+ Pricing Profile</button><button class="btn secondary small" data-action="add-extension-profile">+ Extension Profile</button></div></div><div class="list">${s.pricingProfiles.map(p=>`<div class="list-row"><div><div class="list-title">${escapeHtml(p.name)}</div><div class="list-sub">${s.packages.filter(x=>x.profileId===p.id).length} packages</div></div></div>`).join('')}</div></div><div class="split"><div class="card"><div class="page-head"><div><h1 style="font-size:20px">Ride Packages</h1><p>Tap-friendly packages shown at the counter.</p></div><button class="btn primary small" data-action="add-package">+ Package</button></div><div class="list">${s.packages.sort((a,b)=>a.sort-b.sort).map(p=>`<div class="list-row"><div><div class="list-title">${escapeHtml(p.name)}</div><div class="list-sub">${p.minutes} min • ${escapeHtml(s.pricingProfiles.find(x=>x.id===p.profileId)?.name||'Profile')}</div></div><div><div class="amount">${money(p.price)}</div><button class="btn ghost small" data-action="edit-package" data-id="${p.id}">Edit</button></div></div>`).join('')}</div></div><div class="card"><div class="page-head"><div><h1 style="font-size:20px">Extensions</h1><p>Quick extra-time buttons for ongoing rides.</p></div><button class="btn primary small" data-action="add-extension">+ Extension</button></div><div class="list">${s.extensions.sort((a,b)=>a.sort-b.sort).map(e=>`<div class="list-row"><div><div class="list-title">${escapeHtml(e.name)}</div><div class="list-sub">+${e.minutes} min</div></div><div><div class="amount">${money(e.price)}</div><button class="btn ghost small" data-action="edit-extension" data-id="${e.id}">Edit</button></div></div>`).join('')}</div></div></div>`;
 if(ownerSection==='battery') return `<div class="card"><div class="page-head"><div><h1 style="font-size:20px">Battery Inventory</h1><p>Track each physical battery as an asset.</p></div><button class="btn primary small" data-action="add-battery">+ Battery</button></div><div class="list">${s.batteries.map(batteryRow).join('')}</div></div><div class="section-title">Battery Types</div><div class="card"><div class="list">${s.batteryTypes.map(bt=>`<div class="list-row"><div><div class="list-title">${escapeHtml(bt.name)}</div><div class="list-sub">${escapeHtml(bt.voltage)} • ${escapeHtml(bt.capacity)} • ${escapeHtml(bt.connector)}</div></div></div>`).join('')}</div><button class="btn secondary" style="margin-top:10px" data-action="add-battery-type">+ Add Battery Type</button></div>`;
 if(ownerSection==='business') return `<div class="card"><h2 style="margin-top:0">Business & Counter Settings</h2><form id="business-form" class="form"><div class="field"><label>Business Name</label><input class="input" name="name" value="${escapeHtml(s.business.name)}"></div><div class="split"><div class="field"><label>Phone</label><input class="input" name="phone" value="${escapeHtml(s.business.phone)}"></div><div class="field"><label>UPI ID</label><input class="input" name="upiId" value="${escapeHtml(s.business.upiId)}"></div></div><div class="split"><div class="field"><label>Operator PIN</label><input class="input" name="operatorPin" inputmode="numeric" value="${escapeHtml(s.business.operatorPin)}"></div><div class="field"><label>Owner PIN</label><input class="input" name="ownerPin" inputmode="numeric" value="${escapeHtml(s.business.ownerPin)}"></div></div><div class="field"><label>Warning before time-up (seconds)</label><input class="input" name="warningSeconds" type="number" min="10" max="300" value="${s.business.warningSeconds}"></div><label class="list-row"><div><div class="list-title">Time-up alarm</div><div class="list-sub">Sound + vibration when a ride reaches zero</div></div><input type="checkbox" name="alarmEnabled" ${s.business.alarmEnabled?'checked':''}></label><button class="btn primary" type="submit">Save Settings</button></form></div>`;
 if(ownerSection==='backup') return `<div class="card"><h2 style="margin-top:0">Local Data Backup</h2><p class="subtle">This version intentionally uses device-local storage. Export backups regularly. Firebase can be connected later through the repository layer.</p><div class="actions"><button class="btn primary" data-action="export-data">Export JSON Backup</button><label class="btn secondary" style="display:inline-block">Import Backup<input id="import-file" type="file" accept="application/json" hidden></label></div></div><div class="card danger-zone" style="margin-top:12px"><h2 style="margin-top:0">Reset Demo Data</h2><p class="subtle">Deletes all local rides, settings and custom configuration on this device.</p><button class="btn danger" data-action="reset-data">Reset Local Data</button></div>`;
 return '';
}

function render(){const s=store.get(); if(!s.currentUser){loginView();return;} if(route==='arena')arenaView(); else if(route==='queue')queueView(); else if(route==='rides')ridesView(); else if(route==='batteries')batteriesView(); else if(route==='owner')ownerView(); else moreView();}

function startRideModal(vehicleId,queueId=null){const s=store.get(),v=s.vehicles.find(x=>x.id===vehicleId),q=queueId?s.queue.find(x=>x.id===queueId):null; if(!v||v.status!=='available')return toast('Vehicle is not available'); const pkgs=s.packages.filter(p=>p.profileId===v.pricingProfileId&&p.active).sort((a,b)=>a.sort-b.sort); if(!pkgs.length)return toast('No active package for this vehicle'); let selected=pkgs[0].id,payment='Cash'; const body=`<form id="start-form" class="form"><div class="field"><label>Customer Name *</label><input class="input" name="customerName" required value="${escapeHtml(q?.name||'')}" placeholder="Enter name"></div><div class="field"><label>Mobile (optional)</label><input class="input" name="mobile" inputmode="tel" value="${escapeHtml(q?.mobile||'')}"></div><div class="field"><label>Select Package</label><div class="choice-grid" id="package-choices">${pkgs.map((p,i)=>`<button type="button" class="choice ${i===0?'selected':''}" data-choice-package="${p.id}"><strong>${escapeHtml(p.name)}</strong><small>${p.minutes} minutes</small><div class="price">${money(p.price)}</div></button>`).join('')}</div><input type="hidden" name="packageId" value="${selected}"></div><div class="field"><label>Payment</label><div class="choice-grid"><button type="button" class="choice selected" data-pay="Cash"><strong>Cash</strong></button><button type="button" class="choice" data-pay="UPI"><strong>UPI</strong></button><button type="button" class="choice" data-pay="Other"><strong>Other</strong></button></div><input type="hidden" name="paymentMethod" value="Cash"></div></form>`; modal(`Start ${escapeHtml(v.code)}`,body,`<button class="btn primary block" data-action="confirm-start" data-vehicle="${v.id}" data-queue="${queueId||''}">Start Ride</button>`)}

function extendModal(rideId){const s=store.get(),r=s.rides.find(x=>x.id===rideId),v=s.vehicles.find(x=>x.id===r?.vehicleId); if(!r||!v)return; const exts=s.extensions.filter(e=>e.profileId===v.extensionProfileId&&e.active).sort((a,b)=>a.sort-b.sort); modal('Extend Ride',`<div class="choice-grid">${exts.map(e=>`<button class="choice" data-action="choose-extension" data-ride="${rideId}" data-ext="${e.id}"><strong>${escapeHtml(e.name)}</strong><small>+${e.minutes} minutes</small><div class="price">${money(e.price)}</div></button>`).join('')||'<div class="empty">No extension options configured.</div>'}</div>`)}
function paymentForExtension(rideId,extId){modal('Extension Payment',`<div class="choice-grid"><button class="choice" data-action="confirm-extension" data-ride="${rideId}" data-ext="${extId}" data-pay="Cash"><strong>Cash</strong></button><button class="choice" data-action="confirm-extension" data-ride="${rideId}" data-ext="${extId}" data-pay="UPI"><strong>UPI</strong></button><button class="choice" data-action="confirm-extension" data-ride="${rideId}" data-ext="${extId}" data-pay="Other"><strong>Other</strong></button></div>`)}
function queueModal(){modal('Add to Queue',`<form id="queue-form" class="form"><div class="field"><label>Customer Name *</label><input class="input" name="name" required autofocus></div><div class="field"><label>Mobile (optional)</label><input class="input" name="mobile" inputmode="tel"></div></form>`,`<button class="btn primary block" data-action="confirm-queue">Add Customer</button>`)}
function serveQueueModal(qid){const avail=store.get().vehicles.filter(v=>v.status==='available'); modal('Select Available Vehicle',`<div class="choice-grid">${avail.map(v=>`<button class="choice" data-action="queue-vehicle" data-id="${v.id}" data-queue="${qid}"><strong>${escapeHtml(v.code)}</strong><small>${escapeHtml(v.name)}</small></button>`).join('')||'<div class="empty">No vehicle available right now.</div>'}</div>`)}
function swapBatteryModal(vehicleId,rideId=null){const s=store.get(),v=s.vehicles.find(x=>x.id===vehicleId); if(!v)return; const ready=s.batteries.filter(b=>{if(b.status!=='ready')return false;const bt=s.batteryTypes.find(x=>x.id===b.typeId);return !bt?.compatibleVehicleTypeIds?.length||bt.compatibleVehicleTypeIds.includes(v.typeId)}); modal(`Battery • ${escapeHtml(v.code)}`,`<div class="notice">Current: ${escapeHtml(vehicleBattery(v).map(b=>b.code).join(', ')||'none')}. Selecting a ready battery moves the current battery to Charging.</div><div class="section-title">Ready batteries</div><div class="choice-grid">${ready.map(b=>`<button class="choice" data-action="confirm-swap" data-vehicle="${v.id}" data-battery="${b.id}" data-ride="${rideId||''}"><strong>🔋 ${escapeHtml(b.code)}</strong><small>${escapeHtml(s.batteryTypes.find(x=>x.id===b.typeId)?.name||'Battery')}</small></button>`).join('')||'<div class="empty">No ready batteries.</div>'}</div>`)}
function pauseModal(rideId){modal('Pause Ride',`<div class="choice-grid">${['Battery change','Vehicle issue','Track issue','Customer request','Other'].map(x=>`<button class="choice" data-action="confirm-pause" data-id="${rideId}" data-reason="${x}"><strong>${x}</strong></button>`).join('')}</div>`)}
function completeModal(rideId){const r=store.get().rides.find(x=>x.id===rideId); modal(r?.status==='time_up'?'Complete Ride':'End Ride',`<p class="subtle">${r?.status==='time_up'?'Mark this ride complete and free the vehicle.':'This ride still has time remaining. Choose why it is ending.'}</p><div class="choice-grid">${['Completed','Customer finished','Vehicle issue','Other'].map(x=>`<button class="choice" data-action="confirm-complete" data-id="${rideId}" data-reason="${x}"><strong>${x}</strong></button>`).join('')}</div>`)}
function rideDetail(id){const s=store.get(),r=s.rides.find(x=>x.id===id),v=s.vehicles.find(x=>x.id===r?.vehicleId),p=s.packages.find(x=>x.id===r?.packageId); if(!r)return; modal(r.number,`<div class="list"><div class="list-row"><div><div class="list-title">Customer</div><div class="list-sub">${escapeHtml(r.customerName)}${r.mobile?` • ${escapeHtml(r.mobile)}`:''}</div></div></div><div class="list-row"><div><div class="list-title">Vehicle</div><div class="list-sub">${escapeHtml(v?.code||'')} • ${escapeHtml(v?.name||'')}</div></div></div><div class="list-row"><div><div class="list-title">Package</div><div class="list-sub">${escapeHtml(p?.name||'')} • ${p?.minutes||0} min</div></div><div class="amount">${money(r.baseAmount)}</div></div>${r.extensions.map(e=>`<div class="list-row"><div><div class="list-title">Extension</div><div class="list-sub">+${e.minutes} min • ${dt(e.ts)}</div></div><div class="amount">${money(e.price)}</div></div>`).join('')}<div class="list-row"><div><div class="list-title">Total</div><div class="list-sub">${escapeHtml(r.paymentMethod)} • ${statusText(r.status)}</div></div><div class="amount">${money(r.totalAmount)}</div></div></div>`)}

function pricingProfileModal(kind='pricing'){const title=kind==='pricing'?'Add Pricing Profile':'Add Extension Profile'; modal(title,`<form id="profile-form" class="form"><input type="hidden" name="kind" value="${kind}"><div class="field"><label>Profile Name</label><input class="input" name="name" required placeholder="e.g. RC Boat Standard"></div></form>`,`<button class="btn primary block" data-action="save-profile">Save Profile</button>`)}

function vehicleStatusModal(id){const v=store.get().vehicles.find(x=>x.id===id); if(!v)return; modal(`Status • ${escapeHtml(v.code)}`,`<div class="choice-grid">${['available','charging','maintenance','inactive'].map(st=>`<button class="choice" data-action="set-vehicle-status" data-id="${id}" data-status="${st}"><strong>${statusText(st)}</strong></button>`).join('')}</div>`)}

function addVehicleModal(editId=null){const s=store.get(),v=editId?s.vehicles.find(x=>x.id===editId):null; modal(v?'Edit Vehicle':'Add Vehicle',`<form id="vehicle-form" class="form"><input type="hidden" name="id" value="${v?.id||''}"><div class="split"><div class="field"><label>Code</label><input class="input" name="code" required value="${escapeHtml(v?.code||`VEH-${String(s.vehicles.length+1).padStart(2,'0')}`)}"></div><div class="field"><label>Name</label><input class="input" name="name" required value="${escapeHtml(v?.name||'')}"></div></div><div class="field"><label>Vehicle Type</label><select class="input" name="typeId">${s.vehicleTypes.map(t=>`<option value="${t.id}" ${v?.typeId===t.id?'selected':''}>${t.icon} ${escapeHtml(t.name)}</option>`).join('')}</select></div><div class="field"><label>Pricing Profile</label><select class="input" name="pricingProfileId">${s.pricingProfiles.map(p=>`<option value="${p.id}" ${v?.pricingProfileId===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Extension Profile</label><select class="input" name="extensionProfileId">${s.extensionProfiles.map(p=>`<option value="${p.id}" ${v?.extensionProfileId===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Notes</label><textarea class="input" name="notes">${escapeHtml(v?.notes||'')}</textarea></div></form>`,`<button class="btn primary block" data-action="save-vehicle">Save Vehicle</button>`)}
function addVehicleTypeModal(){modal('Add Vehicle Type',`<form id="vehicle-type-form" class="form"><div class="field"><label>Name</label><input class="input" name="name" required placeholder="e.g. RC Boat"></div><div class="field"><label>Emoji / Icon</label><input class="input" name="icon" value="🎮"></div></form>`,`<button class="btn primary block" data-action="save-vehicle-type">Save Type</button>`)}
function packageModal(id=null){const s=store.get(),p=id?s.packages.find(x=>x.id===id):null; modal(p?'Edit Package':'Add Package',`<form id="package-form" class="form"><input type="hidden" name="id" value="${p?.id||''}"><div class="field"><label>Name</label><input class="input" name="name" required value="${escapeHtml(p?.name||'')}"></div><div class="split"><div class="field"><label>Minutes</label><input class="input" type="number" min="1" name="minutes" required value="${p?.minutes||5}"></div><div class="field"><label>Price (₹)</label><input class="input" type="number" min="0" name="price" required value="${p?.price||200}"></div></div><div class="field"><label>Pricing Profile</label><select class="input" name="profileId">${s.pricingProfiles.map(x=>`<option value="${x.id}" ${p?.profileId===x.id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><label class="list-row"><span>Active</span><input type="checkbox" name="active" ${p?.active===false?'':'checked'}></label></form>`,`<button class="btn primary block" data-action="save-package">Save Package</button>`)}
function extensionModal(id=null){const s=store.get(),e=id?s.extensions.find(x=>x.id===id):null; modal(e?'Edit Extension':'Add Extension',`<form id="extension-form" class="form"><input type="hidden" name="id" value="${e?.id||''}"><div class="field"><label>Name</label><input class="input" name="name" required value="${escapeHtml(e?.name||'')}" placeholder="+3 min"></div><div class="split"><div class="field"><label>Minutes</label><input class="input" type="number" min="1" name="minutes" required value="${e?.minutes||3}"></div><div class="field"><label>Price (₹)</label><input class="input" type="number" min="0" name="price" required value="${e?.price||100}"></div></div><div class="field"><label>Extension Profile</label><select class="input" name="profileId">${s.extensionProfiles.map(x=>`<option value="${x.id}" ${e?.profileId===x.id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><label class="list-row"><span>Active</span><input type="checkbox" name="active" ${e?.active===false?'':'checked'}></label></form>`,`<button class="btn primary block" data-action="save-extension">Save Extension</button>`)}
function batteryModal(id=null){const s=store.get(),b=id?s.batteries.find(x=>x.id===id):null; modal(b?'Edit Battery':'Add Battery',`<form id="battery-form" class="form"><input type="hidden" name="id" value="${b?.id||''}"><div class="field"><label>Battery Code</label><input class="input" name="code" required value="${escapeHtml(b?.code||`B${String(s.batteries.length+1).padStart(2,'0')}`)}"></div><div class="field"><label>Battery Type</label><select class="input" name="typeId">${s.batteryTypes.map(x=>`<option value="${x.id}" ${b?.typeId===x.id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select class="input" name="status">${['ready','charging','maintenance'].map(st=>`<option value="${st}" ${b?.status===st?'selected':''}>${statusText(st)}</option>`).join('')}</select></div><div class="field"><label>Notes</label><textarea class="input" name="notes">${escapeHtml(b?.notes||'')}</textarea></div></form>`,`<button class="btn primary block" data-action="save-battery">Save Battery</button>`)}
function batteryTypeModal(){const s=store.get();modal('Add Battery Type',`<form id="battery-type-form" class="form"><div class="field"><label>Name</label><input class="input" name="name" required placeholder="3S LiPo"></div><div class="split"><div class="field"><label>Voltage</label><input class="input" name="voltage" placeholder="11.1V"></div><div class="field"><label>Capacity</label><input class="input" name="capacity" placeholder="5000mAh"></div></div><div class="field"><label>Connector</label><input class="input" name="connector" placeholder="XT60"></div><div class="field"><label>Compatible Vehicle Types</label><div class="choice-grid">${s.vehicleTypes.map(t=>`<label class="choice"><input type="checkbox" name="compat" value="${t.id}"> <strong style="display:inline">${t.icon} ${escapeHtml(t.name)}</strong></label>`).join('')}</div><div class="subtle">Leave all unchecked to allow this battery type for every vehicle.</div></div></form>`,`<button class="btn primary block" data-action="save-battery-type">Save Type</button>`)}

app.addEventListener('click',e=>{
 const r=e.target.closest('[data-route]'); if(r){route=r.dataset.route;render();return}
 const lr=e.target.closest('[data-login-role]'); if(lr){loginRole=lr.dataset.loginRole;loginView();return}
 const f=e.target.closest('[data-filter]'); if(f){typeFilter=f.dataset.filter;arenaView();return}
 const os=e.target.closest('[data-owner-section]'); if(os){ownerSection=os.dataset.ownerSection;ownerView();return}
 const el=e.target.closest('[data-action]'); if(!el)return; const a=el.dataset.action;
 if(a==='login'){const pin=$('#pin')?.value||''; if(store.login(loginRole,pin)){route='arena';render()}else toast('Incorrect PIN')}
 else if(a==='logout'){store.logout();route='arena';render()}
 else if(a==='close-modal')closeModal();
 else if(a==='close-modal-bg'&&e.target===el)closeModal();
 else if(a==='start-ride')startRideModal(el.dataset.id);
 else if(a==='quick-queue'||a==='add-queue')queueModal();
 else if(a==='confirm-queue'){const fd=new FormData($('#queue-form')); if(!fd.get('name'))return toast('Enter customer name');store.addQueue(fd.get('name'),fd.get('mobile'));closeModal();render();toast('Added to queue')}
 else if(a==='remove-queue'){store.removeQueue(el.dataset.id);render()}
 else if(a==='serve-queue')serveQueueModal(el.dataset.id);
 else if(a==='queue-vehicle'){const q=el.dataset.queue,v=el.dataset.id;closeModal();startRideModal(v,q)}
 else if(a==='confirm-start'){const fd=new FormData($('#start-form')); try{store.startRide({vehicleId:el.dataset.vehicle,customerName:fd.get('customerName'),mobile:fd.get('mobile'),packageId:fd.get('packageId'),paymentMethod:fd.get('paymentMethod'),queueId:el.dataset.queue||null});closeModal();route='arena';render();toast('Ride started')}catch(err){toast(err.message)}}
 else if(a==='extend-ride')extendModal(el.dataset.id);
 else if(a==='quick-extend')paymentForExtension(el.dataset.ride,el.dataset.ext);
 else if(a==='choose-extension')paymentForExtension(el.dataset.ride,el.dataset.ext);
 else if(a==='confirm-extension'){try{store.extendRide(el.dataset.ride,el.dataset.ext,el.dataset.pay);closeModal();render();toast('Ride extended')}catch(err){toast(err.message)}}
 else if(a==='pause-ride')pauseModal(el.dataset.id);
 else if(a==='confirm-pause'){store.pauseRide(el.dataset.id,el.dataset.reason);closeModal();render();toast('Ride paused')}
 else if(a==='resume-ride'){store.resumeRide(el.dataset.id);render();toast('Ride resumed')}
 else if(a==='complete-ride')completeModal(el.dataset.id);
 else if(a==='confirm-complete'){store.completeRide(el.dataset.id,el.dataset.reason);closeModal();render();toast('Ride completed')}
 else if(a==='ride-detail')rideDetail(el.dataset.id);
 else if(a==='swap-battery')swapBatteryModal(el.dataset.id,el.dataset.ride||null);
 else if(a==='confirm-swap'){const rid=el.dataset.ride;if(rid){const ride=store.get().rides.find(x=>x.id===rid);if(ride&&!ride.pausedAt)store.pauseRide(rid,'Battery change')} try{store.swapBattery(el.dataset.vehicle,el.dataset.battery);closeModal();render();toast('Battery swapped')}catch(err){toast(err.message)}}
 else if(a==='battery-ready'){store.set(s=>{const b=s.batteries.find(x=>x.id===el.dataset.id);if(b){b.status='ready';b.assignedVehicleId=null}});render();toast('Battery ready')}
 else if(a==='battery-charge'){store.set(s=>{const b=s.batteries.find(x=>x.id===el.dataset.id);if(b){b.status='charging';b.assignedVehicleId=null}});render()}
 else if(a==='battery-edit')batteryModal(el.dataset.id);
 else if(a==='add-battery')batteryModal();
 else if(a==='vehicle-status')vehicleStatusModal(el.dataset.id);
 else if(a==='set-vehicle-status'){store.set(s=>{const v=s.vehicles.find(x=>x.id===el.dataset.id);if(v&&v.status!=='in_ride')v.status=el.dataset.status});closeModal();render()}
 else if(a==='add-vehicle')addVehicleModal();
 else if(a==='edit-vehicle')addVehicleModal(el.dataset.id);
 else if(a==='save-vehicle'){const fd=new FormData($('#vehicle-form')); const id=fd.get('id'); store.set(s=>{if(id){const v=s.vehicles.find(x=>x.id===id);Object.assign(v,{code:fd.get('code'),name:fd.get('name'),typeId:fd.get('typeId'),pricingProfileId:fd.get('pricingProfileId'),extensionProfileId:fd.get('extensionProfileId'),notes:fd.get('notes')})}else s.vehicles.push({id:uid('veh'),code:fd.get('code'),name:fd.get('name'),typeId:fd.get('typeId'),status:'available',batteryIds:[],pricingProfileId:fd.get('pricingProfileId'),extensionProfileId:fd.get('extensionProfileId'),notes:fd.get('notes')})});closeModal();ownerView();toast('Vehicle saved')}
 else if(a==='add-vehicle-type')addVehicleTypeModal();
 else if(a==='save-vehicle-type'){const fd=new FormData($('#vehicle-type-form'));store.set(s=>s.vehicleTypes.push({id:uid('vt'),name:fd.get('name'),icon:fd.get('icon')||'🎮',active:true}));closeModal();ownerView()}
 else if(a==='add-pricing-profile')pricingProfileModal('pricing');
 else if(a==='add-extension-profile')pricingProfileModal('extension');
 else if(a==='save-profile'){const fd=new FormData($('#profile-form'));const name=fd.get('name')?.trim();if(!name)return toast('Enter profile name');store.set(s=>{if(fd.get('kind')==='pricing')s.pricingProfiles.push({id:uid('pp'),name,vehicleTypeIds:[]});else s.extensionProfiles.push({id:uid('ep'),name,vehicleTypeIds:[]})});closeModal();ownerView();toast('Profile saved')}
 else if(a==='add-package')packageModal(); else if(a==='edit-package')packageModal(el.dataset.id);
 else if(a==='save-package'){const fd=new FormData($('#package-form'));const id=fd.get('id');store.set(s=>{const obj={name:fd.get('name'),minutes:Number(fd.get('minutes')),price:Number(fd.get('price')),profileId:fd.get('profileId'),active:fd.get('active')==='on'};if(id)Object.assign(s.packages.find(x=>x.id===id),obj);else s.packages.push({id:uid('pkg'),sort:s.packages.length+1,...obj})});closeModal();ownerView();toast('Package saved')}
 else if(a==='add-extension')extensionModal(); else if(a==='edit-extension')extensionModal(el.dataset.id);
 else if(a==='save-extension'){const fd=new FormData($('#extension-form'));const id=fd.get('id');store.set(s=>{const obj={name:fd.get('name'),minutes:Number(fd.get('minutes')),price:Number(fd.get('price')),profileId:fd.get('profileId'),active:fd.get('active')==='on'};if(id)Object.assign(s.extensions.find(x=>x.id===id),obj);else s.extensions.push({id:uid('ext'),sort:s.extensions.length+1,...obj})});closeModal();ownerView();toast('Extension saved')}
 else if(a==='save-battery'){const fd=new FormData($('#battery-form'));const id=fd.get('id');store.set(s=>{const obj={code:fd.get('code'),typeId:fd.get('typeId'),status:fd.get('status'),notes:fd.get('notes')};if(id){const b=s.batteries.find(x=>x.id===id); if(b.status!=='in_use')Object.assign(b,obj); else Object.assign(b,{code:obj.code,typeId:obj.typeId,notes:obj.notes})}else s.batteries.push({id:uid('bat'),assignedVehicleId:null,cycles:0,maintenance:false,...obj})});closeModal();render();toast('Battery saved')}
 else if(a==='add-battery-type')batteryTypeModal();
 else if(a==='save-battery-type'){const fd=new FormData($('#battery-type-form'));store.set(s=>s.batteryTypes.push({id:uid('bt'),name:fd.get('name'),voltage:fd.get('voltage'),capacity:fd.get('capacity'),connector:fd.get('connector'),compatibleVehicleTypeIds:fd.getAll('compat')}));closeModal();ownerView()}
 else if(a==='export-data'){const blob=new Blob([store.export()],{type:'application/json'});const u=URL.createObjectURL(blob),link=document.createElement('a');link.href=u;link.download=`kas-rc-arena-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
 else if(a==='reset-data'){if(confirm('Reset all KAS RC Arena local data on this device?')){store.reset();route='arena';render()}}
});

app.addEventListener('submit',e=>{if(e.target.id==='business-form'){e.preventDefault();const fd=new FormData(e.target);store.set(s=>Object.assign(s.business,{name:fd.get('name'),phone:fd.get('phone'),upiId:fd.get('upiId'),operatorPin:fd.get('operatorPin'),ownerPin:fd.get('ownerPin'),warningSeconds:Number(fd.get('warningSeconds')),alarmEnabled:fd.get('alarmEnabled')==='on'}));toast('Settings saved');ownerView()}});

app.addEventListener('click',e=>{const p=e.target.closest('[data-choice-package]'); if(p){$$('[data-choice-package]').forEach(x=>x.classList.remove('selected'));p.classList.add('selected');$('[name="packageId"]').value=p.dataset.choicePackage}const pay=e.target.closest('[data-pay]');if(pay && pay.closest('#start-form')){$$('[data-pay]',pay.parentElement).forEach(x=>x.classList.remove('selected'));pay.classList.add('selected');$('[name="paymentMethod"]').value=pay.dataset.pay}});

app.addEventListener('change',e=>{if(e.target.id==='import-file'){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{store.import(rd.result);toast('Backup imported');ownerView()}catch{toast('Invalid backup file')}};rd.readAsText(f)}});

function tick(){const s=store.get(); let changed=false; s.rides.forEach(r=>{if(r.status==='active'&&Date.now()>=r.endAt){store.markTimeUp(r.id);changed=true;if(s.business.alarmEnabled&&!alarmed.has(r.id)){alarmed.add(r.id);beep();setTimeout(beep,700);setTimeout(beep,1400)}}}); if(route==='arena'&&s.currentUser){$$('[data-timer]').forEach(el=>{const r=s.rides.find(x=>x.id===el.dataset.timer);if(!r)return;const rem=r.status==='paused'?r.pausedRemainingMs:Math.max(0,r.endAt-Date.now());el.textContent=fmtTime(rem);const card=el.closest('.vehicle-card');card?.classList.toggle('warning',r.status==='active'&&rem<=s.business.warningSeconds*1000);card?.classList.toggle('time-up',r.status==='time_up')}); if(changed)arenaView()}}
setInterval(tick,500);
store.subscribe(()=>{});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
