/* Focused equipment pages; no unbounded battery wall or inventory forms. */
function equipmentPageSize(){return innerWidth<600?4:6}
function equipmentPageState(){return memory.equipmentPage||(memory.equipmentPage={screen:'attention',filter:'all',query:'',page:0,item:null})}
function equipmentPageIsOwner(){return memory.currentUser?.role==='owner'}
function equipmentRefresh(){const focused=document.activeElement?.matches('[data-eq-search]'),position=focused?document.activeElement.selectionStart:null;if(memory.portal==='owner')renderOwnerPortal();else renderBatteries();if(focused){const input=$('[data-eq-search]');input?.focus();if(position!==null)input?.setSelectionRange(position,position)}}
function equipmentGo(screen,options={},push=true){if(!discardOwnerDraft())return;memory.equipmentPage={screen,filter:'all',query:'',page:0,item:null,...options};equipmentRefresh();if(historyReady)setHistory(memory.currentView,memory.portal==='owner'?'ownerModal':null,push?'push':'replace');window.scrollTo({top:0,behavior:'instant'})}
function equipmentTabs(){const s=equipmentPageState().screen,active=s.startsWith('inventory')||s.startsWith('edit')||s==='types'||s==='repairs'?'inventory':s.startsWith('battery')?'batteries':s==='car'?'cars':s;return `<nav class="eq-tabs" aria-label="Equipment pages">${[['attention','To do'],['cars','Cars'],['batteries','Batteries'],...(equipmentPageIsOwner()?[['inventory','Setup']]:[])].map(([id,name])=>`<button data-eq-screen="${id}" ${active===id?'class="active" aria-current="page"':''}>${name}</button>`).join('')}</nav>`}
function equipmentTitle(title,description,back=''){return `<div class="eq-page-heading">${back?`<button class="eq-back" data-eq-screen="${back}">← ${({batteries:'Batteries',cars:'Cars',inventory:'Setup','inventory-cars':'Car inventory','inventory-batteries':'Battery inventory',types:'Hardware types'})[back]||'Back'}</button>`:''}<h3>${esc(title)}</h3><p>${esc(description)}</p></div>`}
function equipmentPager(total){const s=equipmentPageState(),pages=Math.max(1,Math.ceil(total/equipmentPageSize()));s.page=Math.max(0,Math.min(Number(s.page)||0,pages-1));return `<div class="eq-pagination"><span>${total?`${s.page*equipmentPageSize()+1}–${Math.min((s.page+1)*equipmentPageSize(),total)} of ${total}`:'0 items'}</span><div><button class="fin-button" data-eq-page="prev" ${s.page===0?'disabled':''}>Previous</button><button class="fin-button" data-eq-page="next" ${s.page+1>=pages?'disabled':''}>Next</button></div></div>`}
function equipmentSlice(items){const s=equipmentPageState();s.page=Math.max(0,Math.min(Number(s.page)||0,Math.max(0,Math.ceil(items.length/equipmentPageSize())-1)));return items.slice(s.page*equipmentPageSize(),(s.page+1)*equipmentPageSize())}
function equipmentSearch(placeholder){return `<label class="eq-search">Search<input data-eq-search type="search" value="${esc(equipmentPageState().query)}" placeholder="${esc(placeholder)}"></label>`}
function equipmentFilters(items){const s=equipmentPageState();return `<div class="eq-filters" aria-label="Status filters">${items.map(([id,name])=>`<button data-eq-filter="${id}" class="${s.filter===id?'active':''}" aria-pressed="${s.filter===id}">${name}</button>`).join('')}</div>`}
function equipmentStatus(b){return ({needs_charge:'Needs charging',charging:'Charging',ready:'Ready',installed:'Installed',in_use:'In use',maintenance:'In service'})[b.status]||b.status}
function equipmentBatteryAction(b){if(!can('batteryActions'))return '';const action=b.status==='needs_charge'?['charge','Start charging']:b.status==='charging'?['ready','Charged — ready']:b.status==='maintenance'?['ready','Repaired — ready']:null;return action?`<button class="fin-button primary-action" data-eq-battery-action="${action[0]}" data-batt="${esc(b.id)}">${action[1]}</button>`:''}
function equipmentAttentionPage(){const c=wsOperationalCounts(),charge=data.batteries.filter(b=>b.status==='needs_charge').length,charging=data.batteries.filter(b=>b.status==='charging').length,ready=data.batteries.filter(b=>b.status==='ready').length;const tasks=[...(c.battery.length?[['cars','attention',`${c.battery.length} cars need a battery`,'Choose a car, then follow Change battery.','View cars']]:[]),...(charge?[['batteries','needs_charge',`${charge} batteries need charging`,'Connect the battery to the charger first.','View batteries']]:[]),...(charging?[['batteries','charging',`${charging} batteries are charging`,'Mark ready only after physical charging finishes.','Check charging']]:[]),...(c.service.length?[['cars','service',`${c.service.length} cars are in service`,'Return repaired cars to ready.','View cars']]:[])];return `${equipmentTitle('What needs doing?','Start here. Open one task at a time.')}<div class="eq-summary"><div><strong>${c.ready.length}</strong><span>Cars ready</span></div><div><strong>${ready}</strong><span>Spare batteries ready</span></div></div><div class="eq-task-list">${tasks.map(([screen,filter,title,description,label])=>`<article class="eq-task"><div><strong>${title}</strong><p>${description}</p></div><button class="fin-button" data-eq-screen="${screen}" data-eq-target-filter="${filter}">${label}</button></article>`).join('')||'<div class="eq-good">'+svg('i-check')+'<strong>Everything ready</strong><p>Go to Counter to start a ride. Cars and batteries are available above when needed.</p></div>'}</div>`}
function equipmentCarsPage(inventory=false){const s=equipmentPageState(),query=s.query.trim().toLowerCase(),all=data.vehicles.filter(v=>!isSumoVehicle(v)&&(inventory||v.active!==false)),items=all.filter(v=>(inventory||s.filter==='all'||(s.filter==='attention'?vehicleBatteryNeedsChange(v)&&!activeRide(v.id)&&v.manualStatus!=='maintenance':s.filter==='service'?v.manualStatus==='maintenance':vehicleReadyForRide(v)))&&`${v.code} ${v.name}`.toLowerCase().includes(query));return `${equipmentTitle(inventory?'Car inventory':'Choose a car',inventory?'Add a car or edit one saved car.':'Open a car to change its battery or report a problem.',inventory?'inventory':'')}${inventory?'<button class="fin-button primary-action" data-add-vehicle>+ Add car</button>':''}${equipmentSearch('Car name or code')}${inventory?'':equipmentFilters([['all','All'],['ready','Ready'],['attention','Battery needed'],['service','In service']])}<div class="eq-list">${equipmentSlice(items).map(v=>`<article class="eq-row"><button class="eq-row-main" data-eq-${inventory?'edit-car':'car'}="${esc(v.id)}"><strong>${esc(v.name)}</strong><span>${esc(v.code)} · ${v.active===false?'Archived':esc(equipmentVehicleStatusLabel(v))}</span></button><button class="fin-button" data-eq-${inventory?'edit-car':'car'}="${esc(v.id)}">${inventory?'Edit':'Open'} →</button></article>`).join('')||'<div class="ws-empty">No cars match. Try another search or filter.</div>'}</div>${equipmentPager(items.length)}`}
function equipmentBatteriesPage(inventory=false){const s=equipmentPageState(),query=s.query.trim().toLowerCase(),items=data.batteries.filter(b=>(inventory||s.filter==='all'||(s.filter==='installed'?['installed','in_use'].includes(b.status):b.status===s.filter))&&`${b.code} ${vehicle(b.assignedVehicleId)?.name||''} ${batteryType(b.typeId)?.name||''}`.toLowerCase().includes(query)).slice().sort((a,b)=>String(a.code).localeCompare(String(b.code),undefined,{numeric:true}));return `${equipmentTitle(inventory?'Battery inventory':'Find a battery',inventory?'Add batteries or edit one saved battery.':'Search by code, then open a battery for details.',inventory?'inventory':'')}${inventory?'<button class="fin-button primary-action" data-add-battery>+ Add battery</button>':''}${equipmentSearch('Battery code or installed car')}${inventory?'':equipmentFilters([['all','All'],['needs_charge','Needs charge'],['charging','Charging'],['ready','Ready'],['installed','Installed'],['maintenance','In service']])}<div class="eq-list">${equipmentSlice(items).map(b=>`<article class="eq-row"><button class="eq-row-main" data-eq-${inventory?'edit-battery':'battery'}="${esc(b.id)}"><strong>${esc(b.code)} ${wsState(equipmentStatus(b),b.status==='ready'?'ready':b.status==='needs_charge'?'warning':'neutral')}</strong><span>${esc(vehicle(b.assignedVehicleId)?.name||batteryType(b.typeId)?.name||'Spare battery')}</span></button><div class="eq-row-actions">${inventory?`<button class="fin-button" data-eq-edit-battery="${esc(b.id)}">Edit →</button>`:equipmentBatteryAction(b)||`<button class="fin-button" data-eq-battery="${esc(b.id)}">Open →</button>`}</div></article>`).join('')||'<div class="ws-empty">No batteries match. Try another search or filter.</div>'}</div>${equipmentPager(items.length)}`}
function equipmentBatteryPage(){const b=battery(equipmentPageState().item);if(!b)return equipmentTitle('Battery unavailable','Return to the battery list.','batteries');const m=batterySessionMetrics(b),v=vehicle(b.assignedVehicleId),instructions=({needs_charge:'Connect this battery to the charger. Tap Start charging after connecting it.',charging:'Check the charger. Tap Charged — ready only when charging has finished.',ready:'Ready to install. Open Cars and choose the car that needs a battery.',installed:`Installed in ${v?.name||'a car'}. Change it from the car page.`,in_use:`In use in ${v?.name||'a car'}. Change it from the car page.`,maintenance:'Keep this battery out of use until it has been checked and repaired.'})[b.status]||'';return `${equipmentTitle(b.code,equipmentStatus(b),'batteries')}<section class="panel eq-detail"><p class="eq-instruction">${esc(instructions)}</p><div class="eq-detail-stats"><div><span>Used this charge</span><strong>${m.usedMin} min</strong></div><div><span>Charge cycles</span><strong>${b.chargeCycles||0}</strong></div>${can('viewRevenue')?`<div><span>Earned this charge</span><strong>${money(m.earned)}</strong></div>`:''}</div><div class="eq-detail-actions">${equipmentBatteryAction(b)}${v?`<button class="fin-button" data-eq-car="${esc(v.id)}">Open ${esc(v.name)}</button>`:b.status==='ready'?'<button class="fin-button" data-eq-screen="cars">Choose a car</button>':''}${equipmentPageIsOwner()?`<button class="fin-button" data-owner-battery-details="${esc(b.id)}">Charge history</button><button class="fin-button" data-eq-edit-battery="${esc(b.id)}">Edit battery</button>`:''}</div></section>`}
function equipmentSetupPage(){return `${equipmentTitle('Equipment setup','Use this when adding or editing equipment. Daily work stays in To do.')}<div class="eq-setup-links">${[['inventory-cars','Cars','Add, rename or archive a car.'],['inventory-batteries','Batteries','Add batteries and edit their codes.'],['types','Hardware types','Battery specifications and equipment types.'],['repairs','Maintenance history','View previous issues and repairs.']].map(([id,name,description])=>`<button data-eq-screen="${id}"><strong>${name} →</strong><span>${description}</span></button>`).join('')}</div>`}
function equipmentEditorPage(kind,id){const container=document.createElement('div');container.innerHTML=kind==='car'||kind==='type'?ownerFleet():ownerBatteries();const key=({car:'v-name',battery:'b-code',btype:'bt-name',type:'type-name'})[kind],field=container.querySelector(`[data-${key}="${CSS.escape(id||'')}"]`),row=field?.closest('.editor-row');return `${equipmentTitle('Edit '+({car:'car',battery:'battery',btype:'battery type',type:'equipment type'})[kind],'Update the fields, then tap Save.',kind==='car'?'inventory-cars':kind==='battery'?'inventory-batteries':'types')}<section class="panel eq-editor">${row?.outerHTML||'<div class="ws-empty">This item is no longer available.</div>'}</section>`}
function equipmentHTML(){const s=equipmentPageState(),owner=equipmentPageIsOwner();let html='';if(!owner&&(s.screen.startsWith('inventory')||s.screen.startsWith('edit')||s.screen==='types'||s.screen==='repairs')){memory.equipmentPage=null;return equipmentHTML()}
 if(s.screen==='attention')html=equipmentAttentionPage();else if(s.screen==='cars')html=equipmentCarsPage();else if(s.screen==='batteries')html=equipmentBatteriesPage();else if(s.screen==='car'){const v=vehicle(s.item);html=equipmentTitle(v?.name||'Car unavailable','Follow one physical action, then record it here.','cars')+(v?equipmentVehicleCard(v,owner?'owner':'operator'):'')+(owner&&v?`<button class="fin-button eq-edit-link" data-eq-edit-car="${esc(v.id)}">Edit car settings</button>`:'');}else if(s.screen==='battery')html=equipmentBatteryPage();else if(s.screen==='inventory')html=equipmentSetupPage();else if(s.screen==='inventory-cars')html=equipmentCarsPage(true);else if(s.screen==='inventory-batteries')html=equipmentBatteriesPage(true);else if(s.screen.startsWith('edit-'))html=equipmentEditorPage(s.screen.slice(5),s.item);else if(s.screen==='types')html=equipmentTitle('Hardware types','Edit one type at a time. Battery driving rules are in Activities & prices.','inventory')+`<div class="eq-list">${data.batteryTypes.map(t=>`<article class="eq-row"><strong>${esc(t.name)}</strong><button class="fin-button" data-eq-edit-btype="${esc(t.id)}">Edit battery type</button></article>`).join('')}${data.vehicleTypes.filter(t=>t.id!=='type_sumo').map(t=>`<article class="eq-row"><strong>${esc(t.name)}</strong><button class="fin-button" data-eq-edit-type="${esc(t.id)}">Edit equipment type</button></article>`).join('')}</div><div class="eq-detail-actions"><button class="fin-button" data-add-btype>+ Battery type</button><button class="fin-button" data-add-type>+ Equipment type</button></div>`;else if(s.screen==='repairs')html=equipmentTitle('Maintenance history','Saved issues and repairs.','inventory')+ownerMaintenance();else{memory.equipmentPage=null;return equipmentHTML()}
 return `<div class="ws-page eq-workspace">${equipmentTabs()}${html}</div>`}
ownerEquipment=equipmentHTML;
renderBatteries=()=>{if(!$('#view-batteries'))return;if(equipmentPageIsOwner()){$('#view-batteries').replaceChildren();return}$('#view-batteries').innerHTML='<button class="page-back" data-back-counter>← Counter</button>'+equipmentHTML();bindEquipmentPage($('#view-batteries'))};
function bindEquipmentPage(root){
 root.querySelector('[data-back-counter]')?.addEventListener('click',()=>goAppView('arena'));
 root.querySelectorAll('[data-eq-screen]').forEach(b=>b.onclick=()=>equipmentGo(b.dataset.eqScreen,{filter:b.dataset.eqTargetFilter||'all'}));
 root.querySelectorAll('[data-eq-filter]').forEach(b=>b.onclick=()=>equipmentGo(equipmentPageState().screen,{filter:b.dataset.eqFilter,query:equipmentPageState().query},false));
 root.querySelectorAll('[data-eq-page]').forEach(b=>b.onclick=()=>{equipmentPageState().page+=b.dataset.eqPage==='next'?1:-1;equipmentRefresh();if(historyReady)setHistory(memory.currentView,memory.portal==='owner'?'ownerModal':null,'replace');window.scrollTo({top:0,behavior:'instant'})});
 root.querySelector('[data-eq-search]')?.addEventListener('input',e=>{equipmentPageState().query=e.target.value;equipmentPageState().page=0;equipmentRefresh();if(historyReady)setHistory(memory.currentView,memory.portal==='owner'?'ownerModal':null,'replace')});
 for(const kind of ['car','battery','edit-car','edit-battery','edit-btype','edit-type'])root.querySelectorAll(`[data-eq-${kind}]`).forEach(b=>b.onclick=()=>equipmentGo(kind,{item:b.getAttribute('data-eq-'+kind)}));
 root.querySelectorAll('[data-eq-battery-action]').forEach(b=>b.onclick=()=>{if(!can('batteryActions'))return;const bat=battery(b.dataset.batt);if(!bat)return;const valid=(b.dataset.eqBatteryAction==='charge'&&bat.status==='needs_charge')||(b.dataset.eqBatteryAction==='ready'&&['charging','maintenance'].includes(bat.status));if(!valid)return;b.disabled=true;batteryAction(bat.id,b.dataset.eqBatteryAction);equipmentRefresh()});
 for(const prefix of ['owner-equipment','equipment'])for(const [action,fn] of Object.entries({assign:assignRecommendedBattery,swap:openBatterySwap,issue:openMaintenance,repair:markRepaired}))root.querySelectorAll(`[data-${prefix}-${action}]`).forEach(b=>b.onclick=()=>{fn(b.getAttribute(`data-${prefix}-${action}`));if(!['swap','issue'].includes(action))equipmentRefresh()});
 root.querySelectorAll('[data-owner-assign-battery]').forEach(b=>b.onclick=()=>openBatterySwap(b.dataset.ownerAssignBattery));
 root.querySelectorAll('[data-owner-battery-details]').forEach(b=>b.onclick=()=>openBatteryDetails(b.dataset.ownerBatteryDetails));
 if(equipmentPageState().screen.startsWith('edit-'))labelOwnerFields(root);
}
const equipmentFocus=focusOwnerField;focusOwnerField=selector=>{const match=selector.match(/data-(v-name|b-code|bt-name|type-name)="([^"]+)"/);if(match&&!$(selector)){equipmentGo('edit-'+({'v-name':'car','b-code':'battery','bt-name':'btype','type-name':'type'})[match[1]],{item:match[2]});}equipmentFocus(selector)};

const equipmentVehicleLabel=equipmentVehicleStatusLabel;equipmentVehicleStatusLabel=v=>{if(!activeRide(v.id)&&v.manualStatus!=='maintenance'&&!vehicleReadyForRide(v)){if(!activityForVehicle(v))return 'Activity disabled';if(vehicleBatteryNeedsChange(v))return 'Battery needed';return 'No package ready'}return equipmentVehicleLabel(v)};
