/* Partners & investment: presentation of the existing finance ledger. */
const FINANCE_KINDS={capital:'Investment',payout:'Profit payout',capital_return:'Capital returned',allocation:'Profit allocated'};
const financeCents=n=>Math.round(Number(n||0)*100)/100;
function partnerBalance(p){const f=data.finance,entries=f.ledger.filter(e=>e.partnerId===p.id),sum=kind=>financeCents(entries.filter(e=>e.kind===kind).reduce((n,e)=>n+Number(e.amount||0),0));const contributed=sum('capital'),returned=sum('capital_return'),paid=sum('payout'),allocated=financeCents(f.allocations.reduce((n,a)=>n+Number(a.shares[p.id]||0),0));return {contributed,returned,paid,allocated,payable:financeCents(allocated-paid),capitalLeft:financeCents(contributed-returned)}}
function financeInitials(name){return String(name||'Partner').trim().split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase()}
function financePercent(value,total){return total>0?Math.max(0,Math.min(100,Number(value||0)/total*100)):0}
function financeProgress(value,label){return `<div class="fin-progress" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(value*10)/10}"><span style="width:${value}%"></span></div>`}
function financeMetric(label,value,helper,icon,accent=''){return `<article class="fin-metric ${accent}"><div class="fin-metric-label"><span>${label}</span>${svg(icon)}</div><strong>${money(value)}</strong><small>${helper}</small></article>`}
function financePartnerCard(p,index){const b=partnerBalance(p);let nextPayment=b.payable;try{nextPayment=settlementPlan(p.id).total}catch{};return `<article class="fin-partner-card"><div class="fin-partner-head"><span class="fin-avatar tone-${index}">${esc(financeInitials(p.name))}</span><div><h3>${esc(p.name)}</h3><span>${p.share}% share of new profit allocations</span></div></div><div class="fin-payable"><span>Profit still payable</span><strong>${money(b.payable)}</strong></div><dl class="fin-partner-metrics"><div><dt>Invested</dt><dd>${money(b.contributed)}</dd></div><div><dt>Profit allocated</dt><dd>${money(b.allocated)}</dd></div><div><dt>Profit paid</dt><dd>${money(b.paid)}</dd></div><div><dt>Capital returned</dt><dd>${money(b.returned)}</dd></div></dl><div class="fin-paid-progress"><div><span>Allocated profit paid</span><strong>${b.allocated?financePercent(b.paid,b.allocated).toFixed(0)+'%':'—'}</strong></div>${financeProgress(financePercent(b.paid,b.allocated),`${p.name}: allocated profit paid`)}<small>${b.allocated?`${money(b.paid)} of ${money(b.allocated)} paid`:'No profit allocated yet'}</small></div>${nextPayment>b.payable?`<div class="fin-next-payment"><span>Next payment including new profit</span><strong>${money(nextPayment)}</strong></div>`:''}<div class="fin-partner-actions"><button type="button" class="fin-button" data-fin-entry="capital" data-fin-partner="${esc(p.id)}">Add investment</button><button type="button" class="fin-button primary-action" data-settle="${esc(p.id)}" ${(b.payable+(financeTotals().available*p.share/100))<=0?'disabled':''}>Pay ${esc(p.name)}</button></div></article>`}
function financeDashboardHTML(){const f=data.finance,t=financeTotals(),rawCoverage=t.capital>0?Math.max(0,t.profit)/t.capital*100:0,needed=Math.max(0,t.capital-t.profit),payable=financeCents(t.allocated-t.payouts),above=financeCents(t.profit-t.capital);return `<div class="finance-dashboard">
 <header class="fin-heading"><div><h3>Partners & investment</h3><p>See what you invested, earned and paid to each partner.</p></div><div class="fin-heading-actions"><button class="fin-button" type="button" data-fin-dialog="financeEntryDialog">${svg('i-plus')} Record money</button><button class="fin-button primary-action" type="button" data-settle="all" ${(payable+t.available)<=0?'disabled':''}>Pay partners</button></div></header>
 <div class="fin-period">All-time totals <span>From completed sessions and recorded entries</span></div>
 <div class="fin-metrics">${financeMetric('Total invested',t.capital,'Contributions from both partners','i-battery')}${financeMetric('Net earnings',t.profit,'Completed sales minus operating costs','i-history',t.profit<0?'loss':'positive')}${financeMetric('Available to allocate',t.available,'Earnings not assigned to partners','i-plus')}${financeMetric('Profit still payable',payable,'Allocated profit minus payouts','i-users','payable')}</div>
 ${t.profit<t.allocated?`<div class="fin-alert" role="status">Allocations exceed current net earnings by <strong>${money(t.allocated-t.profit)}</strong>. Review costs and earlier allocations before making payouts.</div>`:''}
 <div class="fin-overview-grid"><section class="fin-surface fin-recovery"><div class="fin-section-title"><div><h4>Investment coverage</h4><p>How much of your investment is covered by net earnings</p></div><span class="fin-percent">${t.capital?rawCoverage.toFixed(1)+'%':'—'}</span></div>${financeProgress(financePercent(Math.max(0,t.profit),t.capital),'Investment covered by earnings')}<div class="fin-progress-labels"><span>Net earnings <strong>${money(t.profit)}</strong></span><span>Invested <strong>${money(t.capital)}</strong></span></div><p class="fin-recovery-note">${!t.capital?'Record your initial contributions to see progress.':above>=0?`${money(above)} earned above the investment`:`${money(needed)} more earnings needed to cover investment`}</p><div class="fin-capital-return"><div><span>Capital actually returned</span><strong>${money(t.returned)}</strong></div><small>${money(Math.max(0,t.capital-t.returned))} capital still outstanding</small></div><small class="fin-footnote">Earnings coverage is not money paid back to partners.</small></section>
 <section class="fin-surface fin-earnings"><div class="fin-section-title"><div><h4>Where earnings stand</h4><p>A simple breakdown of recorded earnings</p></div></div><dl class="fin-earnings-rows"><div><dt>Completed sales</dt><dd>${money(t.revenue)}</dd></div><div><dt>Operating costs</dt><dd>− ${money(t.costs)}</dd></div><div class="fin-net-row"><dt>Net earnings</dt><dd>${money(t.profit)}</dd></div><div><dt>Assigned to partners</dt><dd>${money(t.allocated)}</dd></div><div class="fin-retained-row"><dt>Unallocated earnings</dt><dd>${money(t.available)}</dd></div></dl><p class="fin-footnote">Unallocated earnings are not a bank balance. Capital and profit payouts are tracked separately.</p></section></div>
 <div class="fin-section-heading"><div><h4>Partner balances</h4><p>Contributions and profit share are tracked separately.</p></div><button class="fin-text-button" type="button" data-fin-dialog="financePartnersDialog">Edit partners & shares</button></div>
 <div class="fin-partners">${f.partners.map(financePartnerCard).join('')}</div>
 <section class="fin-surface fin-split"><div><h4>Agreed profit split</h4><p>Applied to new allocations. Earlier splits stay unchanged.</p></div><div class="fin-share-visual"><div class="fin-split-bar" aria-hidden="true">${f.partners.map((p,i)=>`<span class="tone-${i}" style="width:${Math.max(0,Math.min(100,Number(p.share)||0))}%"></span>`).join('')}</div><div class="fin-share-labels">${f.partners.map((p,i)=>`<span><i class="fin-share-dot tone-${i}"></i>${esc(p.name)} <strong>${p.share}%</strong></span>`).join('')}</div></div></section>
 <section class="fin-surface fin-ledger"><div class="fin-section-title"><div><h4>Money history</h4><p>Investments, allocations and payouts in one ledger</p></div><span class="fin-count">${f.ledger.length+f.allocations.length} records</span></div><div class="fin-ledger-filters"><label><span>Search</span><input data-finance-search type="search" placeholder="Name or note" aria-label="Search money history"></label><label><span>Entry type</span><select data-finance-filter="kind"><option value="all">All entries</option>${Object.entries(FINANCE_KINDS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label><span>Partner</span><select data-finance-filter="partner"><option value="all">Both partners</option>${f.partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label></div><div id="financeLedgerRows" class="fin-ledger-rows"></div><div class="fin-ledger-footer"><span id="financeLedgerCount"></span><div><button class="fin-button" type="button" data-finance-page="prev">Previous</button><button class="fin-button" type="button" data-finance-page="next">Next</button></div></div></section>
 <p class="fin-accounting-note">Figures use recorded sales and expenses, before tax and depreciation.</p>
 <details class="fin-manual-options"><summary>Advanced: allocate profit without paying</summary><p>Use this only to reserve earnings for a later payout.</p><button class="fin-button" type="button" data-fin-dialog="financeAllocateDialog" ${t.available<=0?'disabled':''}>Allocate only</button></details>${financeEntryDialog()}${financeAllocationDialog(t)}${financePartnerDialog()}${settlementDialog()}
 </div>`}
function financeDialogHead(title,description,id){return `<header class="fin-dialog-head"><div><h3>${title}</h3><p>${description}</p></div><button type="button" class="fin-dialog-close session-back" aria-label="Back from ${title}" data-fin-close="${id}">← Back</button></header>`}
function financeEntryDialog(){return `<dialog class="fin-dialog" id="financeEntryDialog" aria-label="Record partner money">${financeDialogHead('Record partner money','Record the money that actually moved.','financeEntryDialog')}<form id="osLedger"><div class="fin-form-grid"><label>Partner<select name="partnerId">${data.finance.partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label><label>Entry type<select name="kind"><option value="capital">Add investment</option><option value="payout">Pay partner profit</option><option value="capital_return">Return capital</option></select></label></div><div class="fin-form-help" id="financeEntryHelp" aria-live="polite"></div><label>Amount (₹)<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="0.00" required></label><label>Payment method<select name="paymentMethod"><option value="">Not specified</option>${data.settings.paymentMethods.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('')}</select></label><label>Note<input name="note" required maxlength="200" placeholder="e.g. Initial car investment"></label><div class="fin-dialog-actions"><button class="fin-button" type="button" data-fin-close="financeEntryDialog">Cancel</button><button class="fin-button primary-action" type="submit">Save entry</button></div></form></dialog>`}
function financeAllocationDialog(t){return `<dialog class="fin-dialog" id="financeAllocateDialog" aria-label="Allocate profit">${financeDialogHead('Allocate profit','Assign earnings to partners using the agreed split.','financeAllocateDialog')}<form id="osAllocate"><div class="fin-dialog-available"><span>Available to allocate</span><strong>${money(t.available)}</strong></div><label>Amount to allocate (₹)<input name="amount" type="number" min="0.01" step="0.01" max="${t.available}" inputmode="decimal" placeholder="0.00" required></label><div id="financeAllocationPreview" class="fin-allocation-preview" aria-live="polite"></div><p class="fin-footnote">Allocation creates a partner balance. Record a payout when you actually pay them.</p><div class="fin-dialog-actions"><button class="fin-button" type="button" data-fin-close="financeAllocateDialog">Cancel</button><button class="fin-button primary-action" type="submit">Confirm allocation</button></div></form></dialog>`}
function financePartnerDialog(){return `<dialog class="fin-dialog" id="financePartnersDialog" aria-label="Partner details">${financeDialogHead('Partner details','Update names and the split for future allocations.','financePartnersDialog')}<form id="osPartners">${data.finance.partners.map((p,i)=>`<fieldset><legend>Partner ${i+1}</legend><div class="fin-form-grid"><label>Name<input name="name_${p.id}" value="${esc(p.name)}" maxlength="60" required></label><label>Profit share (%)<input name="share_${p.id}" type="number" min="0" max="100" step="0.01" value="${p.share}" required></label></div></fieldset>`).join('')}<p class="fin-form-help">Shares must total 100%. Historical allocations keep their saved split.</p><div class="fin-dialog-actions"><button class="fin-button" type="button" data-fin-close="financePartnersDialog">Cancel</button><button class="fin-button primary-action" type="submit">Save partners</button></div></form></dialog>`}
function financeHistory(){const f=data.finance;return [...f.ledger.map((e,i)=>({...e,order:i,partners:[e.partnerId]})),...f.allocations.map((a,i)=>({...a,kind:'allocation',note:'Profit split allocated to partners',order:f.ledger.length+i,partners:Object.keys(a.shares)}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))||(Number(b.createdAt||0)-Number(a.createdAt||0))||b.order-a.order)}
function bindFinanceDashboard(root){
 if(memory.currentUser?.role!=='owner')return;let page=0;const pageSize=8;
 function showHistory(){const kind=root.querySelector('[data-finance-filter="kind"]').value,partner=root.querySelector('[data-finance-filter="partner"]').value,query=root.querySelector('[data-finance-search]').value.trim().toLowerCase(),f=data.finance;const rows=financeHistory().filter(e=>(kind==='all'||e.kind===kind)&&(partner==='all'||e.partners.includes(partner))&&`${e.note} ${FINANCE_KINDS[e.kind]} ${e.partners.map(id=>f.partners.find(p=>p.id===id)?.name||'').join(' ')}`.toLowerCase().includes(query));page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(rows.length/pageSize)-1)));const displayed=rows.slice(page*pageSize,(page+1)*pageSize);root.querySelector('#financeLedgerRows').innerHTML=displayed.length?displayed.map(e=>{const allocation=e.kind==='allocation',names=e.partners.map(id=>f.partners.find(p=>p.id===id)?.name||'Partner'),amount=allocation&&partner!=='all'?Number(e.shares[partner]||0):e.amount;return `<article class="fin-ledger-row"><span class="fin-entry-icon ${esc(e.kind)}">${svg(allocation?'i-users':e.kind==='capital'?'i-plus':'i-history')}</span><div class="fin-entry-detail"><div><strong>${esc(allocation&&partner==='all'?'Both partners':allocation?f.partners.find(p=>p.id===partner)?.name:names.join(', '))}</strong><span class="fin-entry-badge ${esc(e.kind)}">${esc(FINANCE_KINDS[e.kind]||e.kind)}</span></div><p>${esc(e.note||'—')}</p><small>${esc(prettyDate(e.date))}${e.paymentMethod?` · ${esc(e.paymentMethod)}`:''}${allocation?` · ${e.partners.map(id=>`${esc(f.partners.find(p=>p.id===id)?.name||'Partner')}: ${money(e.shares[id])}`).join(' / ')}`:''}</small></div><strong class="fin-entry-amount">${money(amount)}</strong></article>`}).join(''):`<div class="fin-empty">${f.ledger.length+f.allocations.length?'No records match these filters.':'No money recorded yet. Add the partners’ contributions to start tracking investment.'}</div>`;root.querySelector('#financeLedgerCount').textContent=rows.length?`${page*pageSize+1}–${Math.min((page+1)*pageSize,rows.length)} of ${rows.length} records`:'0 records';root.querySelector('[data-finance-page="prev"]').disabled=page===0;root.querySelector('[data-finance-page="next"]').disabled=(page+1)*pageSize>=rows.length;}
 root.querySelectorAll('[data-finance-filter],[data-finance-search]').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{page=0;showHistory()}));root.querySelectorAll('[data-finance-page]').forEach(b=>b.onclick=()=>{page+=b.dataset.financePage==='next'?1:-1;showHistory()});showHistory();
 function showDialog(id){const dialog=root.querySelector('#'+id);if(!dialog)return;dialog.showModal();dialog.querySelector('input,select')?.focus()}
 function dismiss(id){const dialog=root.querySelector('#'+id);if(dialog.dataset.saving==='true')return;if(ownerDraft&&!confirm('Discard the changes in this form?'))return;dialog.close();markOwnerSaved()}
 root.querySelectorAll('[data-fin-close]').forEach(b=>b.onclick=()=>dismiss(b.dataset.finClose));root.querySelectorAll('.fin-dialog').forEach(dialog=>dialog.addEventListener('cancel',e=>{e.preventDefault();dismiss(dialog.id)}));
 root.querySelectorAll('[data-fin-dialog]').forEach(b=>b.onclick=()=>{if(b.dataset.finDialog==='financeEntryDialog'){root.querySelector('#osLedger').reset();updateEntryHelp()}if(b.dataset.finDialog==='financeAllocateDialog'){root.querySelector('#osAllocate').reset();updateAllocationPreview()}showDialog(b.dataset.finDialog)});
 root.querySelectorAll('[data-fin-entry]').forEach(b=>b.onclick=()=>{const form=root.querySelector('#osLedger');form.reset();form.elements.partnerId.value=b.dataset.finPartner;form.elements.kind.value=b.dataset.finEntry;updateEntryHelp();showDialog('financeEntryDialog')});
 function updateEntryHelp(){const form=root.querySelector('#osLedger'),p=data.finance.partners.find(p=>p.id===form.elements.partnerId.value),b=partnerBalance(p),kind=form.elements.kind.value,limit=kind==='payout'?b.payable:kind==='capital_return'?b.capitalLeft:null,input=form.elements.amount;root.querySelector('#financeEntryHelp').textContent=kind==='capital'?'Money contributed by this partner increases their investment.':kind==='payout'?`${money(Math.max(0,b.payable))} profit is available to pay ${p.name}.`:`${money(Math.max(0,b.capitalLeft))} capital can be returned to ${p.name}.`;if(limit!==null)input.max=String(Math.max(0,limit));else input.removeAttribute('max');form.querySelector('[type="submit"]').disabled=limit!==null&&limit<=0;form.elements.note.placeholder=kind==='capital'?'e.g. Initial car investment':kind==='payout'?'e.g. October profit payout':'e.g. Capital repayment';}
 root.querySelector('#osLedger').querySelectorAll('select').forEach(e=>e.addEventListener('change',updateEntryHelp));updateEntryHelp();
 bindSettlementUI(root);
 function updateAllocationPreview(){const value=Number(root.querySelector('#osAllocate').elements.amount.value)||0,t=financeTotals(),[p1,p2]=data.finance.partners,first=financeCents(value*p1.share/100),second=financeCents(value-first);root.querySelector('#financeAllocationPreview').innerHTML=`<div><span>${esc(p1.name)} · ${p1.share}%</span><strong>${money(first)}</strong></div><div><span>${esc(p2.name)} · ${p2.share}%</span><strong>${money(second)}</strong></div><div class="fin-preview-left"><span>Left unallocated</span><strong>${money(Math.max(0,t.available-value))}</strong></div>${value>t.available?'<p class="fin-preview-error">Amount exceeds available earnings.</p>':''}`;}
 root.querySelector('#osAllocate input').addEventListener('input',updateAllocationPreview);updateAllocationPreview();
}
