/* Automatic allocation + payout. Records payments; never initiates transfers. */
function settlementPlan(target='all',reserve=data.finance.reserveAmount||0){
 const f=data.finance,t=financeTotals(),partners=f.partners;if(partners.length!==2||partners.some(p=>!Number.isFinite(Number(p.share))||Number(p.share)<0)||Math.abs(partners.reduce((n,p)=>n+Number(p.share),0)-100)>.001)throw Error('Partner shares must total 100%.');if(target!=='all'&&!partners.some(p=>p.id===target))throw Error('Partner unavailable.');const reserveCents=Math.round(Number(reserve)*100);if(!Number.isFinite(reserveCents)||reserveCents<0)throw Error('Enter a valid reserve.');const availableCents=Math.max(0,Math.round(t.available*100)),newCents=Math.max(0,availableCents-reserveCents),first=Math.round(newCents*Number(partners[0].share)/100),split={[partners[0].id]:first/100,[partners[1].id]:(newCents-first)/100};const payouts=partners.map(p=>{const due=Math.round(partnerBalance(p).payable*100);if(due<0)throw Error('Review an overpaid partner balance first.');return {partnerId:p.id,name:p.name,existing:due/100,newShare:split[p.id],amount:(due+Math.round(split[p.id]*100))/100}}).filter(p=>target==='all'||p.partnerId===target);const total=financeCents(payouts.reduce((n,p)=>n+p.amount,0)),fingerprint=JSON.stringify({capital:t.capital,profit:t.profit,allocated:t.allocated,payouts:t.payouts,partners:partners.map(p=>({id:p.id,share:p.share,due:partnerBalance(p).payable})),reserve:reserveCents,target});return {target,reserve:reserveCents/100,newAllocation:newCents/100,shares:split,payouts,total,unallocatedLeft:(availableCents-newCents)/100,fingerprint};
}
async function recordSettlement(plan,id,method){
 if(memory.currentUser?.role!=='owner')throw Error('Owner access required.');const f=data.finance;f.settlements=Array.isArray(f.settlements)?f.settlements:[];if(f.settlements.some(s=>s.id===id))return {alreadyRecorded:true};if(!data.settings.paymentMethods.includes(method))throw Error('Choose the payment method.');const latest=settlementPlan(plan.target,plan.reserve);if(latest.fingerprint!==plan.fingerprint)throw Error('Balances changed. Reopen the payment summary before recording.');if(latest.total<=0)throw Error('No profit is available to pay.');const previous=structuredClone(f),now=Date.now(),createdBy=actor();
 if(latest.newAllocation>0)f.allocations.push({id:uid('allocation'),createdAt:now,date:localDateKey(now),amount:latest.newAllocation,shares:latest.shares,settlementId:id,createdBy});
 latest.payouts.filter(p=>p.amount>0).forEach(p=>f.ledger.push({id:uid('ledger'),createdAt:now,date:localDateKey(now),partnerId:p.partnerId,kind:'payout',amount:p.amount,note:'Partner payment — automatic allocation included',paymentMethod:method,settlementId:id,createdBy}));
 f.reserveAmount=latest.reserve;f.settlements.push({id,createdAt:now,date:localDateKey(now),target:latest.target,amount:latest.total,newAllocation:latest.newAllocation,reserveAmount:latest.reserve,paymentMethod:method,partnerAmounts:Object.fromEntries(latest.payouts.map(p=>[p.partnerId,p.amount])),createdBy});
 try{save();await persistQueue}catch(e){data.finance=previous;throw Error('Payment could not be saved. Please check storage and try again.')}return {amount:latest.total};
}
function partnerCashAdjustment(start,end=start){return financeCents((data.finance?.ledger||[]).filter(e=>e.paymentMethod==='Cash'&&dateInRange(e.date,start,end)).reduce((n,e)=>n+(e.kind==='capital'?Number(e.amount||0):['payout','capital_return'].includes(e.kind)?-Number(e.amount||0):0),0))}
function settlementDialog(){return `<dialog class="fin-dialog" id="financeSettlementDialog" aria-label="Record partner payment">${financeDialogHead('Pay partners','Allocation and payment are recorded together.','financeSettlementDialog')}<form id="financeSettlementForm"><label>Keep unallocated in business (₹)<input name="reserve" type="number" min="0" step="0.01" inputmode="decimal" value="${Number(data.finance.reserveAmount||0)}"></label><div id="settlementPreview" class="fin-allocation-preview" aria-live="polite"></div><label>Paid using<select name="method">${data.settings.paymentMethods.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('')}</select></label><p class="fin-footnote">Confirm after you have paid. This records the payment; it does not transfer money.</p><div id="settlementError" class="fin-preview-error" role="alert"></div><div class="fin-dialog-actions"><button type="button" class="fin-button" data-fin-close="financeSettlementDialog">Cancel</button><button type="submit" class="fin-button primary-action" id="confirmSettlement">Record payment</button></div></form></dialog>`}
function bindSettlementUI(root){
 let plan=null,token=null,busy=false;const dialog=root.querySelector('#financeSettlementDialog'),form=root.querySelector('#financeSettlementForm');if(!dialog)return;
 function preview(){try{plan=settlementPlan(dialog.dataset.target||'all',form.elements.reserve.value);root.querySelector('#settlementError').textContent='';root.querySelector('#settlementPreview').innerHTML=plan.payouts.map(p=>`<div class="settlement-partner"><span><strong>${esc(p.name)}</strong><small>${money(p.existing)} unpaid + ${money(p.newShare)} new share</small></span><strong>${money(p.amount)}</strong></div>`).join('')+`<div class="fin-preview-left"><span>New profit allocated to both partners</span><strong>${money(plan.newAllocation)}</strong></div><div><span>Left unallocated</span><strong>${money(plan.unallocatedLeft)}</strong></div>`;root.querySelector('#confirmSettlement').textContent=`Record ${money(plan.total)} paid`;root.querySelector('#confirmSettlement').disabled=plan.total<=0;}catch(e){plan=null;root.querySelector('#settlementError').textContent=e.message;root.querySelector('#confirmSettlement').disabled=true}}
 root.querySelectorAll('[data-settle]').forEach(button=>button.onclick=()=>{token=uid('settlement');dialog.dataset.target=button.dataset.settle;form.elements.reserve.value=Number(data.finance.reserveAmount||0);preview();dialog.showModal()});form.elements.reserve.addEventListener('input',preview);
 form.onsubmit=async e=>{e.preventDefault();if(busy||!plan)return;busy=true;dialog.dataset.saving='true';root.querySelector('#confirmSettlement').disabled=true;try{const result=await recordSettlement(plan,token,form.elements.method.value);dialog.close();renderOwner();render();toast(result.alreadyRecorded?'Already recorded':`${money(result.amount)} partner payment recorded`)}catch(error){root.querySelector('#settlementError').textContent=error.message;busy=false;delete dialog.dataset.saving;root.querySelector('#confirmSettlement').disabled=false}};
}
