const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{
 const server=require('http').createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname,file=path.join(__dirname,'..',name==='/'?'index.html':name);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.wav':'audio/wav'})[path.extname(file)]||'application/octet-stream');if(!fs.existsSync(file)){res.statusCode=404;res.end();return}fs.createReadStream(file).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.KAS_BROWSER_EXECUTABLE?{executablePath:process.env.KAS_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});const errors=[];
 try{for(const width of [320,390,768,1366]){const pageSize=width<600?4:6,context=await browser.newContext({viewport:{width,height:width===1366?900:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>data.activities);async function capture(name){if(process.env.KAS_QA_SCREENSHOT_DIR&&[390,1366].includes(width)){fs.mkdirSync(process.env.KAS_QA_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.KAS_QA_SCREENSHOT_DIR,name+'-'+width+'.png')})}}
 await page.locator('[data-login-role=owner]').click();await page.locator('#ownerLoginPin').fill('1234');await page.locator('#ownerLoginBtn').click();assert(await page.locator('#counterWorkspace').isVisible());assert(await page.locator('#ownerModal').isHidden());assert.equal(await page.evaluate(()=>memory.currentView),'arena');assert.equal(await page.locator('#accountPopover').count(),0);assert.equal(await page.locator('#ownerMenuToggle').count(),0);
 const initial=await page.locator('.topbar').boundingBox();async function menu(){if(width<850&&!await page.locator('#appNavigation').isVisible())await page.locator('#accountToggle').click()}
 await menu();await capture('navigation-menu');assert(await page.locator('[data-app-view=arena]').isVisible());assert.equal(await page.locator('.topbar').boundingBox().then(b=>b.height),initial.height);await page.locator('[data-app-owner=finance]').click();assert(await page.locator('#counterWorkspace').isHidden());assert(await page.locator('#ownerModal').isVisible());assert.equal(await page.locator('[aria-current=page][data-app-owner]').count(),1);assert.equal(await page.evaluate(()=>scrollY),0);if(width<850)assert(await page.locator('#appNavigation').isHidden());
 await page.locator('[data-owner-sub=partners]').click();assert.equal(await page.evaluate(()=>memory.ownerTab),'partners');assert.equal(await page.locator('[aria-current=page][data-app-owner]').count(),1);await page.locator('[data-fin-dialog=financeEntryDialog]').click();await page.goBack();await page.waitForFunction(()=>document.querySelectorAll('dialog:modal').length===0);assert.equal(await page.evaluate(()=>memory.ownerTab),'partners');await page.goBack();await page.waitForFunction(()=>memory.ownerTab==='finance');assert(await page.locator('.ws-eod').isVisible());await page.locator('#backToCounter').click();assert(await page.locator('#counterWorkspace').isVisible());
 await page.locator('[data-os-start]').click();assert(await page.locator('#rideModal').isVisible());const form=await page.locator('#rideModal').boundingBox();assert(Math.abs(form.y-initial.height)<=1);assert(form.width>=width-(width>=850?233:1));assert(await page.locator('#rideModal .session-back').isVisible());await capture('new-session');await page.locator('#rideModal [data-close]').click();await page.waitForFunction(()=>document.querySelector('#rideModal').classList.contains('hidden'));assert(await page.locator('#counterWorkspace').isVisible());
 await menu();await page.locator('[data-app-view=batteries]').click();assert(await page.locator('.eq-good').isVisible());assert.equal(await page.locator('.eq-row').count(),0);await page.locator('.eq-tabs [data-eq-screen=batteries]').click();
 await page.evaluate(()=>{for(let i=8;i<=50;i++)data.batteries.push({...structuredClone(data.batteries[2]),id:'qa-bat-'+i,code:'B'+String(i).padStart(2,'0'),assignedVehicleId:null,status:'ready'});data.batteries.find(b=>b.code==='B09').status='needs_charge';data.batteries.find(b=>b.code==='B10').status='charging';equipmentRefresh()});assert.equal(await page.locator('.eq-row').count(),pageSize);assert((await page.locator('.eq-pagination').innerText()).includes('of 50'));await capture('fifty-batteries');await page.locator('[data-eq-page=next]').click();assert((await page.locator('.eq-pagination').innerText()).includes(`${pageSize+1}–${pageSize*2}`));
 await page.locator('[data-eq-search]').fill('B09');assert.equal(await page.locator('.eq-row').count(),1);assert.equal(await page.locator('[data-eq-search]').inputValue(),'B09');assert.equal(await page.evaluate(()=>ownerDraft),false);await page.locator('[data-eq-battery-action=charge]').click();assert.equal(await page.evaluate(()=>data.batteries.find(b=>b.code==='B09').status),'charging');await page.locator('[data-eq-battery-action=ready]').click();assert.equal(await page.evaluate(()=>data.batteries.find(b=>b.code==='B09').status),'ready');
 await page.locator('[data-eq-battery]').first().click();assert((await page.locator('.eq-page-heading').innerText()).includes('B09'));await page.goBack();await page.waitForFunction(()=>equipmentPageState().screen==='batteries');assert.equal(await page.locator('[data-eq-search]').inputValue(),'B09');assert.equal(await page.locator('.eq-row').count(),1);
 await page.locator('[data-eq-screen=attention]').click();assert((await page.locator('.eq-task').innerText()).includes('1 batteries are charging'));await page.locator('[data-eq-target-filter=charging]').click();assert.equal(await page.locator('.eq-row').count(),1);assert((await page.locator('.eq-row').innerText()).includes('B10'));assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 await page.evaluate(()=>navigateOwner('pricing'));await page.locator('[data-p-price]').first().fill('177');page.once('dialog',d=>d.dismiss());await menu();await page.locator('[data-app-view=arena]').click();assert.equal(await page.evaluate(()=>memory.ownerTab),'pricing');assert.equal(await page.evaluate(()=>memory.portal),'owner');await page.evaluate(()=>markOwnerSaved());await page.reload();await page.waitForFunction(()=>memory.currentUser?.role==='owner');assert(await page.locator('#counterWorkspace').isVisible());assert(await page.locator('#ownerModal').isHidden());assert.equal(await page.evaluate(()=>data.batteries.length),50);
 await page.evaluate(()=>{logout();data.staff[0].permissions.batteryActions=false;login('operator',data.staff[0])});assert(await page.locator('#counterWorkspace').isVisible());await menu();assert.equal(await page.locator('[data-app-owner]').count(),0);await page.locator('[data-app-view=batteries]').click();assert.equal(await page.locator('[data-eq-screen=inventory]').count(),0);await page.locator('.eq-tabs [data-eq-screen=batteries]').click();assert.equal(await page.locator('.eq-row').count(),pageSize);assert.equal(await page.locator('[data-eq-battery-action]').count(),0);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await context.close();}
 assert.deepEqual(errors,[]);console.log('PASS: real owner PIN login and reload land on Counter; one menu/sidebar; stable header; one active page; Back restores owner/equipment tabs and search; full-screen ride; 50-battery responsive paging/search/action; draft guard; operator access.');}
 finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
