const vm=require('vm'),fs=require('fs'),path=require('path'),assert=require('assert');
const el=()=>({onclick:null,addEventListener(){},classList:{add(){},remove(){},toggle(){}},dataset:{},style:{},value:'',childNodes:[{}]});const nodes={};
const context={console,structuredClone,Date,Math,Set,Number,String,JSON,Array,Infinity,document:{documentElement:{style:{setProperty(){}}},querySelector:s=>nodes[s]||(nodes[s]=el()),querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){},visualViewport:null},navigator:{},location:{},Audio:function(){},sessionStorage:{getItem(){return null}},localStorage:{getItem(){return null}},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},URL,Blob,history:{},confirm:()=>true};
vm.createContext(context);for(const file of ['app.js','activity-os.js','finance-ui.js','settlement.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);const run=s=>vm.runInContext(s,context);
function reset(profit=1000){run(`data=normalizeOperationalState(structuredClone(DEFAULT));memory.currentUser={role:'owner'};data.rides=[{id:'r',date:localDateKey(),endedAt:1,baseAmount:${profit},extensions:[],payments:[{method:'Cash',amount:${profit}}]}];save=()=>{persistQueue=Promise.resolve()};`)}
(async()=>{
 reset();run("data.finance.allocations.push({id:'old',amount:200,shares:{p1:100,p2:100}});data.finance.ledger.push({kind:'payout',partnerId:'p1',amount:40});var plan=settlementPlan('all',300)");
 assert.equal(run('plan.newAllocation'),500);assert.equal(run('plan.total'),660);assert.equal(run('plan.unallocatedLeft'),300);
 await run("recordSettlement(plan,'payment-1','Cash')");assert.equal(run('financeTotals().allocated'),700);assert.equal(run('financeTotals().payouts'),700);assert.equal(run('financeTotals().profit'),1000);assert.equal(run('data.finance.settlements.length'),1);assert.equal(run('partnerCashAdjustment(localDateKey())'),-660);
 const duplicate=await run("recordSettlement(plan,'payment-1','Cash')");assert.equal(duplicate.alreadyRecorded,true);assert.equal(run('data.finance.ledger.length'),3);
 assert.equal(run("settlementPlan('all',300).total"),0);await assert.rejects(run("recordSettlement(settlementPlan('all',300),'empty','Cash')"),/No profit/);
 reset(100.01);await run("recordSettlement(settlementPlan('p1',0),'single-1','UPI')");assert.equal(run('data.finance.allocations[0].shares.p1'),50.01);assert.equal(run('data.finance.allocations[0].shares.p2'),50);assert.equal(run('data.finance.ledger[0].amount'),50.01);
 run('data.finance.partners[0].share=80;data.finance.partners[1].share=20');await run("recordSettlement(settlementPlan('p2',0),'single-2','UPI')");assert.equal(run('data.finance.allocations.length'),1);assert.equal(run('data.finance.ledger[1].amount'),50);assert.equal(run('partnerCashAdjustment(localDateKey())'),0);
 reset();run("var stale=settlementPlan('all',0);data.expenses.push({amount:20})");await assert.rejects(run("recordSettlement(stale,'stale','Cash')"),/Balances changed/);assert.equal(run('data.finance.allocations.length'),0);
 run("memory.currentUser={role:'operator'}");await assert.rejects(run("recordSettlement(settlementPlan('all',0),'staff','Cash')"),/Owner access/);run("memory.currentUser={role:'owner'}");await assert.rejects(run("recordSettlement(settlementPlan('all',0),'invalid-method','Card')"),/payment method/);
 assert.throws(()=>run("settlementPlan('all',-1)"),/valid reserve/);run('data.finance.partners[0].share=60');assert.throws(()=>run("settlementPlan('all',0)"),/100%/);
 reset();run("save=()=>{persistQueue=Promise.reject(Error('Storage unavailable'))}");await assert.rejects(run("recordSettlement(settlementPlan('all',0),'failure','Cash')"),/could not be saved/);assert.equal(run('data.finance.ledger.length'),0);assert.equal(run('data.finance.allocations.length'),0);assert.equal(run('data.finance.settlements.length'),0);
 reset();run("data.finance.ledger=[{kind:'capital',partnerId:'p1',amount:200,date:localDateKey(),paymentMethod:'Cash'},{kind:'capital_return',partnerId:'p1',amount:50,date:localDateKey(),paymentMethod:'Cash'},{kind:'capital',partnerId:'p2',amount:200,date:localDateKey(),paymentMethod:'UPI'},{kind:'capital',partnerId:'p1',amount:999,date:'2000-01-01',paymentMethod:'Cash'},{kind:'capital',partnerId:'p1',amount:999,date:localDateKey()}]");assert.equal(run('partnerCashAdjustment(localDateKey())'),150);assert.equal(run("partnerCashAdjustment('2000-01-01',localDateKey())"),1149);
 console.log('PASS: combined allocation/payout, existing unpaid balance, retained reserve, exact cent split, single-partner frozen shares, repeated-id protection, stale balance rejection, owner access, storage rollback, and dated Cash/UPI reconciliation.');
})().catch(e=>{console.error(e);process.exit(1)});
