/* Run against a previous complete release: KAS_PREVIOUS_RELEASE=/path/to/v4.4. */
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{
 if(!process.env.KAS_PREVIOUS_RELEASE)throw Error('Set KAS_PREVIOUS_RELEASE to the extracted v4.4 folder.');let root=process.env.KAS_PREVIOUS_RELEASE;
 const server=require('http').createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.join(root,pathname==='/'?'index.html':pathname);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.wav':'audio/wav'})[path.extname(file)]||'application/octet-stream');if(!fs.existsSync(file)){res.statusCode=404;res.end();return}fs.createReadStream(file).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({...(process.env.KAS_BROWSER_EXECUTABLE?{executablePath:process.env.KAS_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});
 try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>data.activities);await page.evaluate(()=>login('owner'));
 await page.evaluate(async()=>{await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));const now=Date.now();data.rides=[{id:'prior',date:localDateKey(now),endedAt:now,baseAmount:1000,extensions:[],payments:[{method:'Cash',amount:1000}]}];data.finance.ledger=[{id:'capital',date:localDateKey(),kind:'capital',partnerId:'p1',amount:5000,note:'Existing investment'}];data.finance.allocations=[{id:'allocation',date:localDateKey(),amount:200,shares:{p1:100,p2:100}}];await dbSet(data)});
 assert((await page.evaluate(()=>caches.keys())).includes('kas-activityos-v4.4'));root=path.join(__dirname,'..');await page.reload();await page.waitForFunction(()=>typeof settlementPlan==='function'&&memory.currentUser?.role==='owner');assert.equal(await page.evaluate(()=>data.rides[0].id),'prior');assert.equal(await page.evaluate(()=>financeTotals().capital),5000);assert.equal(await page.evaluate(()=>data.finance.allocations.length),1);assert(await page.locator('#counterWorkspace').isVisible());assert(await page.locator('#ownerModal').isHidden());
 await page.evaluate(async()=>{await navigator.serviceWorker.getRegistration().then(r=>r.update());await navigator.serviceWorker.ready});await page.waitForFunction(async()=> (await caches.keys()).includes('kas-activityos-v4.5'));await page.waitForFunction(async()=>!(await caches.keys()).includes('kas-activityos-v4.4'));
 await page.evaluate(()=>navigateOwner('partners'));await page.locator('[data-settle=all]').click();await page.locator('#confirmSettlement').click();await page.waitForFunction(()=>data.finance.settlements.length===1&&document.querySelectorAll('dialog:modal').length===0);assert.equal(await page.evaluate(()=>financeTotals().payouts),1000);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>memory.currentUser?.role==='owner');assert.equal(await page.evaluate(()=>data.finance.settlements.length),1);assert.equal(await page.evaluate(()=>financeTotals().payouts),1000);await page.evaluate(()=>navigateOwner('partners'));assert(await page.locator('[data-settle=all]').isDisabled());assert(await page.locator('.fin-partner-card').count()===2);await page.evaluate(()=>navigateOwner('activities'));assert(await page.locator('.ws-policy').count()>0);await page.evaluate(()=>goAppView('batteries'));assert(await page.locator('.eq-tabs').isVisible());await page.locator('[data-eq-screen=batteries]').click();assert(await page.locator('.eq-row').count()===4);assert.deepEqual(errors,[]);
 console.log('PASS: v4.4 cached upgrade to v4.5, unchanged investment/prior allocation/session, retired old assets, combined payout persists, and new navigation and equipment pages work after offline reload.');}
 finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
