const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{
 const server=require('http').createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.join(__dirname,'..',pathname==='/'?'index.html':pathname);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.wav':'audio/wav'})[path.extname(file)]||'application/octet-stream');if(!fs.existsSync(file)){res.statusCode=404;res.end();return}fs.createReadStream(file).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({...(process.env.KAS_BROWSER_EXECUTABLE?{executablePath:process.env.KAS_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});const errors=[];
 try{for(const size of [{width:320,height:740},{width:390,height:844},{width:768,height:1024},{width:1366,height:900}]){
  const context=await browser.newContext({viewport:size}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>data.activities);await page.evaluate(()=>login('owner'));
  async function capture(name){if(process.env.KAS_QA_SCREENSHOT_DIR&&[390,1366].includes(size.width)){fs.mkdirSync(process.env.KAS_QA_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.KAS_QA_SCREENSHOT_DIR,`${name}-${size.width}.png`),fullPage:true})}}
  for(const tab of ['overview','operations','equipment','activities','pricing','finance','partners','staff','settings','backup']){
   await page.evaluate(tab=>navigateOwner(tab),tab);assert(!/sumo/i.test(await page.locator('#ownerContent').innerText()),tab+' visible Sumo');assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),tab+' viewport overflow');await capture(tab);
  }
  await page.evaluate(()=>navigateOwner('activities'));await page.locator('.ws-policy .ws-edit summary').first().click();await page.locator('[data-os-policy] [name=safe]').first().fill('22');await page.locator('[data-os-policy] [name=reserve]').first().fill('6');await page.locator('[data-os-policy] button').first().click();assert.equal(await page.evaluate(()=>data.batteryTypes[0].safeMinutes),22);assert.equal(await page.evaluate(()=>data.batteryTypes[0].reserveMinutes),6);
  await page.evaluate(()=>navigateOwner('pricing'));const packageId=await page.locator('[data-p-price]').first().getAttribute('data-p-price');await page.locator(`[data-p-price="${packageId}"]`).fill('125');await page.locator(`[data-save-package="${packageId}"]`).click();assert.equal(await page.evaluate(id=>packageBy(id).price,packageId),125);
  await page.evaluate(()=>navigateOwner('equipment'));const batteryCount=await page.evaluate(()=>data.batteries.length);await page.locator('[data-eq-screen=inventory]').click();await page.locator('[data-eq-screen=inventory-batteries]').click();await page.locator('[data-add-battery]').click();assert(await page.locator('[data-b-code]').last().isVisible());assert.equal(await page.evaluate(()=>data.batteries.length),batteryCount+1);
  await page.evaluate(()=>navigateOwner('staff'));await page.locator('[data-staff-name]').fill('Counter Team');await page.locator('[data-save-staff]').click();assert.equal(await page.evaluate(()=>data.staff[0].name),'Counter Team');assert.equal(await page.locator('[data-staff-pin]').getAttribute('type'),'password');
  await page.evaluate(()=>navigateOwner('partners'));assert(await page.locator('[data-settle=all]').isDisabled());await page.evaluate(()=>{const now=Date.now();data.rides=[{id:'sample',date:localDateKey(now),endedAt:now,baseAmount:1000,extensions:[],payments:[{method:'Cash',amount:1000}]}];data.expenses=[];renderOwnerPortal()});
  await page.locator('[data-settle=all]').click();await page.locator('#financeSettlementForm [name=reserve]').fill('200');assert((await page.locator('#settlementPreview').innerText()).includes('₹400'));await capture('settlement');await page.locator('#confirmSettlement').click();await page.waitForFunction(()=>data.finance.settlements.length===1&&document.querySelectorAll('dialog:modal').length===0);assert.equal(await page.evaluate(()=>financeTotals().allocated),800);assert.equal(await page.evaluate(()=>financeTotals().payouts),800);assert.equal(await page.evaluate(()=>financeTotals().profit),1000);
  // A saved reserve can be reduced from the same shortcut, without manual allocation.
  assert(await page.locator('[data-settle=all]').isEnabled());await page.locator('[data-settle=all]').click();assert(await page.locator('#confirmSettlement').isDisabled());await page.locator('#financeSettlementForm [name=reserve]').fill('0');await page.locator('#financeSettlementForm [name=method]').selectOption('UPI');
  await page.locator('#confirmSettlement').evaluate(button=>{button.click();button.click()});await page.waitForFunction(()=>data.finance.settlements.length===2&&document.querySelectorAll('dialog:modal').length===0);assert.equal(await page.evaluate(()=>data.finance.allocations.length),2);assert.equal(await page.evaluate(()=>data.finance.ledger.length),4);assert.equal(await page.evaluate(()=>partnerCashAdjustment(localDateKey())), -800);assert(await page.locator('[data-settle=all]').isDisabled());
  await page.evaluate(()=>navigateOwner('finance'));assert.equal(await page.locator('.eod-metric.cash strong').innerText(),'₹200');assert((await page.locator('.ws-cash-adjustment').innerText()).includes('-₹800'));await page.locator('#eodActualCash').fill('200');await page.locator('[data-close-day]').click();assert.equal(await page.evaluate(()=>data.eodClosings[0].expectedCash),200);await page.evaluate(()=>{data.finance.ledger.push({id:'post-close',date:localDateKey(),kind:'capital',partnerId:'p1',amount:100,paymentMethod:'Cash'});renderOwnerPortal()});assert((await page.locator('.eod-closed').innerText()).includes('Closing needs review'));await page.evaluate(()=>{data.finance.ledger=data.finance.ledger.filter(e=>e.id!=='post-close');renderOwnerPortal()});await page.locator('[data-eod-mode=range]').click();assert.equal(await page.locator('.eod-metric.cash strong').innerText(),'₹200');
  await page.evaluate(()=>{memory.eodMode='day';data.rides=[];save();logout();login('operator',data.staff[0])});assert(await page.locator('#ownerModal').isHidden());
  for(const view of ['arena','queue','rides','batteries']){await page.evaluate(view=>switchView(view),view);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),view+' operator overflow');await capture('operator-'+view)}
  await page.evaluate(()=>switchView('arena'));await page.locator('[data-os-start]').click();await page.locator('#startRide').click();assert.equal(await page.evaluate(()=>data.rides.length),1);assert(await page.locator('#fleet .ride-more').first().isVisible());await page.evaluate(()=>{data.rides[0].endsAt=Date.now()-1;renderFleet()});await page.locator('[data-end]').click();assert(await page.evaluate(()=>!!data.rides[0].endedAt));
  await page.evaluate(()=>switchView('queue'));await page.locator('#addQueue').click();await page.locator('#saveQueue').click();assert.equal(await page.evaluate(()=>data.queue[0].name),'Q-001');assert((await page.locator('#wsQueueSummary').innerText()).includes('1 waiting'));await context.close();
 }assert.deepEqual(errors,[]);console.log('PASS: all owner/operator pages on mobile & desktop, no Sumo/overflow, editable pricing and battery policy, inventory add focus, staff save, payment preview/reserve, combined payout, double-click guard, day/range cash closing, operator ride and queue.');}
 finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
